version: "3.8"

services:
  image-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: image-service
    env_file:
      - .env
    ports:
      - "8056:8056"
    depends_on:
      - mongodb
      - kafka
      - redis
      - eureka-server
    networks:
      - craftpilot-network
    restart: unless-stopped
    healthcheck:
      test: curl -f http://localhost:8056/actuator/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 60s

networks:
  craftpilot-network:
    external: true
