server:
  port: 8053
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
  shutdown: graceful

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: notification-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
    include: kafka-base
  sendgrid:
    api-key: ${SPRING_SENDGRID_API_KEY}
    enabled: true
    from: ${SPRING_SENDGRID_FROM_EMAIL:support@craftpilot.com}
  mail:
    sendgrid:
      api-key: ${SENDGRID_API_KEY}
      from: ${SENDGRID_FROM_EMAIL}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://mongodb:27017/notification_service}
      database: ${MONGO_INITDB_DATABASE:notification_service}
      auto-index-creation: true
      repositories:
        type: reactive
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:13579ada}
      timeout: 10000
      connect-timeout: 10000
      client-type: lettuce
      ssl:
        enabled: false
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
        shutdown-timeout: 200ms
        cluster:
          refresh:
            adaptive: true
            period: 30s
  cloud:
    discovery:
      enabled: true
    stream:
      bindings:
        notificationEventConsumer-in-0:
          destination: notifications
          group: notification-service-group
        notificationEventProducer-out-0:
          destination: notifications

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: mongodb,redis
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    redis:
      enabled: true
    mongodb:
      enabled: true
    db:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://craftpilot:13579ada@eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10

resilience4j:
  circuitbreaker:
    instances:
      notificationService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      notificationService:
        maxAttempts: 3
        waitDuration: 1s
  ratelimiter:
    instances:
      notificationService:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 5s

logging:
  level:
    root: INFO
    "[com.craftpilot.notificationservice]": INFO
    "[org.springframework.data]": INFO
    "[org.springframework.security]": INFO
    "[org.springframework.web]": INFO
    "[org.springframework.cloud]": INFO
    com.craftpilot: DEBUG
    org.springframework: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true
  packages-to-scan: com.craftpilot.notificationservice.controller
  paths-to-match: /**
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  topics:
    notification-events: notification-events
    notification-delivery: notification-delivery
