server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  security:
    basic:
      enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:3000"
              - "https://craftpilot.io"
              - "https://*.craftpilot.io"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposed-headers:
              - "Access-Control-Allow-Origin"
              - "Access-Control-Allow-Credentials"
              - "X-Total-Count"
      routes:
        - id: llm-service
          uri: lb://llm-service
          predicates:
            - Path=/ai/**
          filters:
            - name: CircuitBreaker
              args:
                name: llmServiceCircuitBreaker
                fallbackUri: forward:/fallback
          metadata:
            connect-timeout: 30000
            response-timeout: 30000

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/auth/**

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

      httpclient:
        connect-timeout: 10000
        response-timeout: 10000

eureka:
  instance:
    prefer-ip-address: true
    hostname: api-gateway
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true

# Basit endpointler için erişim ver
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.craftpilot: DEBUG
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG

# Firebase
firebase:
  credentials-file: firebase-service-account.json
