server:
  port: ${SERVER_PORT:8080}
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
    min-response-size: 1024

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  security:
    basic:
      enabled: false
    filter:
      order: 1
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
      client:
        composite-indicator:
          enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Core Services
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/auth/**
          metadata:
            response-timeout: 5000
            connect-timeout: 2000
            secured: true # Authentication gerekli
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user-service
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                key-resolver: "#{@userKeyResolver}"

        - id: auth-service
          uri: lb://user-service
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=0
            - PreserveHostHeader
          metadata:
            secured: false # Authentication bypass for auth endpoints

        # Business Services
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          metadata:
            secured: true
            roles: [ADMIN] # Sadece ADMIN rolü erişebilir
          filters:
            - StripPrefix=1

        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/analytics/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: analyticsServiceCircuitBreaker

        - id: llm-service
          uri: lb://llm-service
          predicates:
            - Path=/ai/**
          metadata:
            connect-timeout: 120000
            response-timeout: 120000
            secured: true
          filters:
            - name: CircuitBreaker
              args:
                name: llmServiceCircuitBreaker
                fallbackUri: forward:/fallback/ai-fallback
            - AddRequestHeader=Content-Type, application/json
            - AddRequestHeader=Accept, text/event-stream
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/images/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: imageServiceCircuitBreaker

        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/credits/**
          filters:
            - name: CircuitBreaker
              args:
                name: creditServiceCircuitBreaker

        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/subscriptions/**,/subscription-plans/**,/payments/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: subscriptionServiceCircuitBreaker

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: notificationServiceCircuitBreaker

        - id: redis-service
          uri: lb://redis-service
          predicates:
            - Path=/cache/**
          filters:
            - StripPrefix=1
            - name: CircuitBreaker
              args:
                name: redisServiceCircuitBreaker

      default-filters:
        - AddRequestHeader=X-Forwarded-Prefix, /
        - name: Retry
          args:
            retries: 3
            methods: GET,POST,PUT,DELETE,OPTIONS
            series: SERVER_ERROR
            exceptions:
              - java.io.IOException
              - java.util.concurrent.TimeoutException
        - name: RequestSize
          args:
            maxSize: 10MB
        - AddResponseHeader=X-Response-Time, ${responseTime}
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:13579ada}

  httpclient:
    connect-timeout: 30000
    response-timeout: 30000
    pool:
      max-idle-time: 15s
      max-connections: 1000
      type: ELASTIC
      metrics: true
      acquire-timeout: 60000
  loadbalancer:
    cache:
      enabled: true
      caffeine:
        spec: maximumSize=500,expireAfterWrite=5s
  jackson:
    deserialization:
      UNWRAP_ROOT_VALUE: true
      FAIL_ON_UNKNOWN_PROPERTIES: false
      ACCEPT_SINGLE_VALUE_AS_ARRAY: true
    serialization:
      WRAP_ROOT_VALUE: true
      FAIL_ON_EMPTY_BEANS: false
    mapper:
      ACCEPT_CASE_INSENSITIVE_PROPERTIES: true
      DEFAULT_VIEW_INCLUSION: true

eureka:
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:api-gateway}
    instance-id: ${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    metadata-map:
      zone: primary
      profile: ${spring.profiles.active:prod}
      management.context-path: ${server.servlet.context-path:/actuator}
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://craftpilot:${EUREKA_PASSWORD:13579ada}@eureka-server:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
    should-enforce-registration-at-init: true
    enabled: true
    use-dns-for-fetching-service-urls: false
    availability-zones:
      default: defaultZone

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: ping,redis,diskSpace # db yerine redis ekledik
        liveness:
          include: ping
  health:
    circuitbreakers:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    redis:
      enabled: true # Redis health check'i aktif edildi
    diskspace:
      enabled: true
    validate-group-membership: true

  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      sla:
        http.server.requests: 10ms,50ms,100ms,200ms,500ms
    enable:
      all: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] [%X{traceId}/%X{spanId}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.craftpilot.apigateway: DEBUG
    org.springframework.cloud.gateway: INFO
    org.springframework.cloud.netflix.eureka: ${LOG_LEVEL:INFO}
    com.netflix.discovery: ${LOG_LEVEL:INFO}
    com.craftpilot.apigateway.security: ${SECURITY_LOG_LEVEL:INFO}
    org.springframework.security: INFO
    reactor.netty.http.client: INFO

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: TIME_BASED
        slidingWindowSize: 60
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        eventConsumerBufferSize: 100
    instances:
      llmServiceCircuitBreaker:
        baseConfig: default
        slidingWindowSize: 30
        waitDurationInOpenState: 20s
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        allowHealthIndicatorToFail: true
      userServiceCircuitBreaker:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true
    instances:
      userServiceTimeLimiter:
        timeoutDuration: 2s
      llmServiceTimeLimiter:
        timeoutDuration: 30s

# Tracing Configuration
spring.sleuth:
  sampler:
    probability: 1.0
  baggage:
    correlation-enabled: true
    remote-fields: x-request-id
    local-fields: country-code,user-id

cors:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,https://craftpilot.io,https://*.craftpilot.io}
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  max-age: 3600
  allow-credentials: true
