server:
  port: ${SERVER_PORT:8080}
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
  ssl:
    enabled: true
    key-store: ${SSL_KEYSTORE_PATH:/etc/ssl/keystore.p12}
    key-store-password: ${SSL_KEYSTORE_PASSWORD:your-keystore-password}
    key-store-type: PKCS12
    key-alias: api-gateway

spring:
  application:
    name: api-gateway
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  cloud:
    gcp:
      project-id: ${GCP_PROJECT_ID:craft-pilot-ai}
      credentials:
        location: classpath:firebase-service-account.json
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      httpclient:
        connect-timeout: 2000
        response-timeout: 5s
        pool:
          max-idle-time: 15s
          type: elastic
          max-connections: 1000
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter.replenishRate: ${RATE_LIMITER_REPLENISH_RATE:10}
            redis-rate-limiter.burstCapacity: ${RATE_LIMITER_BURST_CAPACITY:20}
            redis-rate-limiter.requestedTokens: ${RATE_LIMITER_REQUESTED_TOKENS:1}
            key-resolver: "#{@userKeyResolver}"
        - name: CircuitBreaker
          args:
            name: defaultCircuitBreaker
            fallbackUri: forward:/fallback
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
              - "https://craftpilot.io"
              - "https://app.craftpilot.io"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders:
              - "X-User-ID"
              - "X-User-Email"
              - "X-User-Role"
            maxAge: 3600
      routes:
        # User Service Routes
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker
                fallbackUri: forward:/fallback/user

        # Admin Service Routes
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/api/admin/**
          filters:
            - name: CircuitBreaker
              args:
                name: adminServiceCircuitBreaker
                fallbackUri: forward:/fallback/admin

        # Analytics Service Routes
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**
          filters:
            - name: CircuitBreaker
              args:
                name: analyticsServiceCircuitBreaker
                fallbackUri: forward:/fallback/analytics

        # LLM Service Routes
        - id: llm-service
          uri: lb://llm-service
          predicates:
            - Path=/api/questions/**
          filters:
            - name: CircuitBreaker
              args:
                name: llmServiceCircuitBreaker
                fallbackUri: forward:/fallback/llm

        # Credit Service Routes
        - id: credit-service
          uri: lb://credit-service
          predicates:
            - Path=/api/credits/**
          filters:
            - name: CircuitBreaker
              args:
                name: creditServiceCircuitBreaker
                fallbackUri: forward:/fallback/credit

        # Swagger UI Routes
        - id: swagger-ui-user
          uri: lb://user-service
          predicates:
            - Path=/user-service/swagger-ui/**,/user-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: swagger-ui-admin
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/swagger-ui/**,/admin-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: swagger-ui-analytics
          uri: lb://analytics-service
          predicates:
            - Path=/analytics-service/swagger-ui/**,/analytics-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: swagger-ui-llm
          uri: lb://llm-service
          predicates:
            - Path=/llm-service/swagger-ui/**,/llm-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: swagger-ui-credit
          uri: lb://credit-service
          predicates:
            - Path=/credit-service/swagger-ui/**,/credit-service/v3/api-docs/**
          filters:
            - StripPrefix=1

        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: 0
      timeout: 10000
      connect-timeout: 10000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:secret}@eureka-server:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
    instance-id: ${spring.application.name}:${server.port}

resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
        registerHealthIndicator: true
      userServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
      adminServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
      analyticsServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
      llmServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
      subscriptionServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
      productServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
      paymentServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
      notificationServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
      codeServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
      contentServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5
      creditServiceCircuitBreaker:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        permittedNumberOfCallsInHalfOpenState: 5

  timelimiter:
    instances:
      default:
        timeoutDuration: 5s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] [%X{spanId}] %-5level %logger{36} - %msg%n"
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    com.craftpilot.apigateway: INFO
    root: INFO

# Service Port Mappings
# api-gateway:           8061
# eureka-server:         8761
# user-service:          8050
# admin-service:         8063
# analytics-service:     8064
# llm-service:    8065
# credit-service:        8068

firebase:
  credentials:
    path: ${FIREBASE_CREDENTIAL_PATH:firebase-service-account.json}
  project:
    id: ${GCP_PROJECT_ID:craft-pilot-ai}
  auth:
    token-cache:
      maximum-size: 1000
      expire-after-write: 3600s

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway
    disable-swagger-default-url: true
    use-root-path: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /v3/api-docs
        name: API Gateway
      - url: /v3/api-docs/auth
        name: Auth Service
      - url: /v3/api-docs/user
        name: User Service
      - url: /v3/api-docs/project
        name: Project Service
      - url: /v3/api-docs/notification
        name: Notification Service
    config-url: /v3/api-docs/swagger-config
    urls-primary-name: API Gateway
    disable-swagger-default-url: true
