server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: api-gateway
  security:
    basic:
      enabled: false
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:3000"
              - "https://craftpilot.io"
              - "https://*.craftpilot.io"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
            exposedHeaders:
              - "X-Total-Count"
            maxAge: 3600
      routes:
        - id: llm-service
          uri: lb://llm-service
          predicates:
            - Path=/ai/**
          filters:
            - PreserveHostHeader
            - name: CircuitBreaker
              args:
                name: llmServiceCircuitBreaker
          metadata:
            connect-timeout: 60000
            response-timeout: 60000

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**,/auth/**
          filters:
            - name: CircuitBreaker
              args:
                name: userServiceCircuitBreaker

        - id: image-service
          uri: lb://image-service
          predicates:
            - Path=/images/**
          filters:
            - StripPrefix=1

        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

        # Diğer servisler burada kısaltıldı

      httpclient:
        connect-timeout: 30000
        response-timeout: 30000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://craftpilot:${EUREKA_PASSWORD:13579ada}@eureka-server:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    root: INFO
    com.craftpilot.apigateway: DEBUG

# Firebase
firebase:
  credentials-file: firebase-service-account.json
