name: Analytics Service CI/CD

on:
  push:
    branches: [master]
    paths:
      - "analytics-service/**"
  workflow_dispatch: # Manuel tetikleme için ekleyin

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Google Cloud kimlik doğrulaması
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # Google Cloud CLI kurulumu
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: Build and Push Docker image
        run: |
          docker build -t craftpilot/analytics-service:latest .
          docker push craftpilot/analytics-service:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Google Cloud kimlik bilgilerini VPS'e kopyala
            echo '${{ secrets.GCP_SA_KEY }}' > /opt/craftpilot/gcp-credentials.json

            docker pull craftpilot/analytics-service:latest
            docker stop analytics-service || true
            docker rm analytics-service || true

            docker run -d \
              --name analytics-service \
              --network craftpilot-network \
              -p 8096:8096 \
              -v /opt/craftpilot/gcp-credentials.json:/gcp-credentials.json:ro \
              -e GOOGLE_APPLICATION_CREDENTIALS=/gcp-credentials.json \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e EUREKA_USERNAME=craftpilot \
              -e EUREKA_PASSWORD=13579ada \
              -e REDIS_HOST=redis \
              -e REDIS_PORT=6379 \
              -e REDIS_PASSWORD=13579ada \
              craftpilot/analytics-service:latest

      - name: Health check
        run: |
          echo "Waiting for service to start..."
          sleep 30
          if curl -f http://localhost:8096/actuator/health; then
            echo "Service is healthy"
          else
            echo "Service failed health check"
            docker logs analytics-service
            exit 1
          fi

      - name: Notify Slack on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
