apiVersion: v1
kind: Service
metadata:
  name: llm-service
  labels:
    app: llm-service
spec:
  type: ClusterIP
  ports:
    - port: 8062
      targetPort: 8062
      protocol: TCP
      name: http
  selector:
    app: llm-service
