apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: craftpilot
data:
  redis-host: "redis-master"
  redis-port: "6379"
  application.yml: |
    server:
      port: 8085

    spring:
      application:
        name: redis-service

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
        metrics:
          enabled: true
        prometheus:
          enabled: true

    logging:
      level:
        com.craftpilot.redisservice: INFO
        org.springframework.data.redis: INFO
        io.lettuce: INFO
