apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-service
  labels:
    app: image-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: image-service
  template:
    metadata:
      labels:
        app: image-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - image-service
                topologyKey: kubernetes.io/hostname
      containers:
        - name: image-service
          image: ${DOCKERHUB_USERNAME}/image-service:latest-arm64
          ports:
            - containerPort: 8056
              name: http
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-port
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: bootstrap-servers
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server:8761"
            - name: SPRING_CLOUD_CONFIG_URI
              value: "http://config-server:8888"
            - name: SERVER_PORT
              value: "8056"
            - name: SPRING_CLOUD_KUBERNETES_ENABLED
              value: "true"
            - name: EUREKA_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eureka-credentials
                  key: username
            - name: EUREKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eureka-credentials
                  key: password
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: SPRING_APPLICATION_NAME
              value: "image-service"
            - name: MANAGEMENT_SERVER_PORT
              value: "8056"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "*"
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-credentials
                  key: uri
            - name: SPRING_DATA_MONGODB_DATABASE
              value: "image-service"
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-credentials
                  key: api-key
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8056
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8056
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8056
            initialDelaySeconds: 40
            periodSeconds: 15
      terminationGracePeriodSeconds: 60
