server:
  port: 6379
  shutdown: graceful

spring:
  application:
    name: redis-service
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000
        shutdown-timeout: 200ms
  cloud:
    gcp:
      project-id: craft-pilot-ai
      credentials:
        location: classpath:firebase-service-account.json
      firestore:
        enabled: true
        project-id: craft-pilot-ai
        database-id: default

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka}
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true

logging:
  level:
    root: DEBUG
    com.craftpilot: DEBUG
    org.springframework.web: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.cloud: DEBUG
    com.netflix.discovery: DEBUG
    org.springframework.boot: DEBUG
