server:
  port: 8067
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
  shutdown: graceful

spring:
  application:
    name: user-memory-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://${MONGO_ROOT_USERNAME:craftpilot}:${MONGO_ROOT_PASSWORD:secure_password}@${MONGODB_HOST:craftpilot-mongodb}:27017/${MONGODB_DATABASE:craftpilot_user_memory_db}?authSource=admin&retryWrites=true&w=majority&serverSelectionTimeoutMS=30000&connectTimeoutMS=20000&socketTimeoutMS=60000}
      database: ${MONGODB_DATABASE:craftpilot_user_memory_db}
      auto-index-creation: true
      connect-timeout: 60000
      socket-timeout: 60000
      max-wait-time: 120000
      max-connection-idle-time: 300000
      max-connection-life-time: 600000
      retry-writes: true
      max-connection-pool-size: 20
      min-connection-pool-size: 5
      server-selection-timeout: 60000
  cloud:
    kubernetes:
      config:
        enabled: true
        name: user-memory-service-config
      reload:
        enabled: true
        mode: polling
        period: 1000
    discovery:
      enabled: true
      client:
        health-indicator:
          enabled: true
        simple:
          instances:
            eureka-server:
              - uri: http://eureka-server:8761
                metadata:
                  management.port: ${management.server.port:8761}

# Enable Swagger UI and API docs
springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    enabled: true
    path: /v3/api-docs

# Actuator yapılandırmaları ekleniyor/düzenleniyor
management:
  server:
    port: ${SERVER_PORT:8067}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      group:
        readiness:
          include: readinessState,diskSpace,ping,mongo
        liveness:
          include: livenessState
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    defaults:
      enabled: true
    mongodb:
      enabled: true

# Mevcut yapılandırmayı koruyalım
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: ${EUREKA_INSTANCE_HOSTNAME:user-memory-service}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      management.port: ${management.server.port:8067}

user-memory:
  cleanup:
    days: 30

llm-service:
  url: ${LLM_SERVICE_URL:http://localhost:8062}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.craftpilot: ${LOGGING_LEVEL_COM_CRAFTPILOT:INFO}
    org.springframework.cloud.netflix.eureka: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_NETFLIX_EUREKA:INFO}
    org.springframework.data.mongodb: ${LOGGING_LEVEL_MONGODB:INFO}

resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  timelimiter:
    instances:
      default:
        timeoutDuration: 5s
        cancelRunningFuture: true

# MongoDB koleksiyon isimlendirme konfigürasyonu
mongodb:
  collection:
    user-memory: user_memories
    user-instruction: user_instructions
    response-preference: response_preferences
