server:
  port: 8092
  shutdown: graceful

spring:
  application:
    name: subscription-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
    include: kafka-base
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:13579ada}
    timeout: 2000
    database: ${REDIS_DATABASE:0}
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1ms
      shutdown-timeout: 100ms
  cache:
    type: redis
    redis:
      time-to-live: 1800000 # 30 minutes
      cache-null-values: false
  cloud:
    function:
      definition: processSubscriptionEvent;processPaymentEvent
    stream:
      bindings:
        processSubscriptionEvent-in-0:
          destination: subscription-events
          group: subscription-service-group
        processPaymentEvent-in-0:
          destination: payment-events
          group: subscription-service-group
  # MongoDB yapılandırması
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://${MONGO_ROOT_USERNAME:craftpilot}:${MONGO_ROOT_PASSWORD:secure_password}@${MONGODB_HOST:craftpilot-mongodb}:27017/${MONGODB_DATABASE:craftpilot_subscription_db}?authSource=admin&retryWrites=true&w=majority&serverSelectionTimeoutMS=30000&connectTimeoutMS=20000&socketTimeoutMS=60000}
      database: ${MONGODB_DATABASE:craftpilot_subscription_db}
      auto-index-creation: true
      # Bağlantı parametreleri
      connect-timeout: 30000
      socket-timeout: 60000
      max-wait-time: 120000
      max-connection-idle-time: 300000
      max-connection-life-time: 600000
      # MongoDB dayanıklılık ayarları
      retry-writes: true
      max-connection-pool-size: 20
      min-connection-pool-size: 5
      server-selection-timeout: 60000
  service-registry:
    auto-registration:
      enabled: true
  discovery:
    enabled: true

iyzico:
  api-key: ${IYZICO_API_KEY:sandbox-api-key}
  secret-key: ${IYZICO_SECRET_KEY:sandbox-secret-key}
  base-url: ${IYZICO_BASE_URL:https://sandbox-api.iyzipay.com}

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    health:
      show-details: always
      probes:
        enabled: true
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    mongodb:
      enabled: true
  server:
    port: 8092

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    syntax-highlight:
      theme: monokai
    try-it-out-enabled: true
    filter: true
  show-actuator: true
  default-produces-media-type: application/json
  default-consumes-media-type: application/json
  writer-with-default-pretty-printer: true

resilience4j:
  circuitbreaker:
    instances:
      subscription-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
      iyzico-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      mongodb-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1000
      mongodb:
        maxAttempts: 3
        waitDuration: 500
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
      mongodb-operations:
        maxAttempts: 5
        waitDuration: 1000
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 1.5
  ratelimiter:
    instances:
      default:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 2s

logging:
  level:
    com.craftpilot.subscriptionservice: DEBUG
    org.springframework.data: INFO
    org.springframework.data.mongodb: INFO
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.kafka: INFO
    org.springframework.web: INFO

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://craftpilot:13579ada@eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:subscription-service}
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

kafka:
  topics:
    subscription-events: subscription-events
    payment-events: payment-events
