spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      retries: 3
      acks: all
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 1
        reconnect.backoff.ms: 1000
        reconnect.backoff.max.ms: 5000
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.craftpilot.*"
        isolation.level: read_committed
        max.poll.records: 500
        heartbeat.interval.ms: 3000
        session.timeout.ms: 45000
    admin:
      auto-create: false
      fail-fast: false
      operation-timeout: 10000
      close-timeout: 10000

kafka:
  enabled: ${KAFKA_ENABLED:true}
  topic:
    partitions: 3
    replicas: 1
