apiVersion: v1
kind: Service
metadata:
  name: aiquestion-service
  labels:
    app: aiquestion-service
spec:
  type: ClusterIP
  ports:
    - port: 8082
      targetPort: 8082
      protocol: TCP
      name: http
  selector:
    app: aiquestion-service
