apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: craftpilot
  labels:
    app: eureka-server
spec:
  replicas: 1 # Eureka Server genellikle tek instance olarak çalışır
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8761"
    spec:
      containers:
        - name: eureka-server
          image: craftpilot/eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: EUREKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eureka-credentials
                  key: password
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 60
            periodSeconds: 15
