apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: craftpilot
  labels:
    app: eureka-server
spec:
  type: ClusterIP
  ports:
    - port: 8761
      targetPort: 8761
      protocol: TCP
      name: http
  selector:
    app: eureka-server
