spring:
  application:
    name: user-service
  config:
    import: classpath:kafka-base.yml
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://${MONGO_ROOT_USERNAME:craftpilot}:${MONGO_ROOT_PASSWORD:secure_password}@${MONGODB_HOST:craftpilot-mongodb}:27017/${MONGODB_DATABASE:craftpilot_user_db}?authSource=admin&retryWrites=true&w=majority&serverSelectionTimeoutMS=30000&connectTimeoutMS=20000&socketTimeoutMS=60000}
      database: ${MONGODB_DATABASE:craftpilot_user_db}
      # Gelişmiş bağlantı parametreleri
      connection-timeout: 30000
      socket-timeout: 60000
      max-connection-idle-time: 300000
      connection-pool-max-size: 20
      auto-index-creation: true
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DATABASE:0}
    password: ${REDIS_PASSWORD:}
    timeout: 2000ms
    client-name: ${spring.application.name}
    connect-timeout: 5000
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 2
        max-wait: -1
  # Firestore'u devre dışı bırak
  cloud:
    gcp:
      firestore:
        enabled: false
      core:
        enabled: false
  # Kafka konfigürasyonu (kafka-base.yml'de temel ayarlar tanımlanmış)
  kafka:
    enabled: ${KAFKA_ENABLED:true}
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    topic:
      user-preferences: ${KAFKA_TOPIC_USER_PREFERENCES:user-preferences}
      user-events: user-events
      activity-events: activity-events

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
    metadata-map:
      user.name: ${eureka.client.security.user.name:craftpilot}
      user.password: ${eureka.client.security.user.password:13579ada}
  client:
    serviceUrl:
      defaultZone: http://${eureka.client.security.user.name:craftpilot}:${eureka.client.security.user.password:13579ada}@${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
    enabled: ${EUREKA_ENABLED:true}
    healthcheck:
      enabled: true
    refresh:
      enable: true
    shouldDisableDelta: true
    registry-fetch-interval-seconds: 30
    security:
      user:
        name: ${EUREKA_USERNAME:craftpilot}
        password: ${EUREKA_PASSWORD:13579ada}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,loggers,env,beans
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: redis,mongo,diskSpace
        liveness:
          include: ping
  health:
    redis:
      enabled: true
    mongo:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
      userOperations:
        baseConfig: default
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 60
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 5
        recordFailurePredicate: com.craftpilot.userservice.exception.UserOperationFailurePredicate
    instances:
      userPreferences:
        baseConfig: default
        slidingWindowSize: 8
        waitDurationInOpenState: 5s
      userRedis:
        baseConfig: default
      redisCircuitBreaker:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        recordExceptions:
          - java.util.concurrent.TimeoutException
          - java.io.IOException
      kafkaPublisher:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 30s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  retry:
    instances:
      userPreferences:
        maxAttempts: 2
        waitDuration: 500ms
      redis:
        maxAttempts: 2
        waitDuration: 250ms
        retryExceptions:
          - java.util.concurrent.TimeoutException
          - java.io.IOException
  timelimiter:
    instances:
      userPreferences:
        timeoutDuration: 3s
        cancelRunningFuture: true

kafka:
  producer:
    timeout: 5
    enabled: true
  retry:
    backoff:
      initial-interval: 1000
      max-interval: 10000
      multiplier: 2.0
    max-attempts: 3

logging:
  level:
    root: INFO
    com.craftpilot: INFO
    org.springframework.data.redis: WARN
    org.springframework.data.mongodb: WARN
    com.craftpilot.redis: INFO

# Kullanıcı tercihleri operasyon timeout değeri
user-preference:
  operation:
    timeout: 1000 # 1 saniye timeout

# AI Model yapılandırmaları
app:
  load-models: ${LOAD_MODELS:true}
  models:
    file: ${MODELS_FILE:newmodels.json}
    version: ${MODELS_VERSION:1}
