spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: kafka-base
  data:
    redis:
      host: ${REDIS_HOST:redis-server}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:13579ada}
      connect-timeout: 10000
      timeout: 10000
      client-type: lettuce
      ssl:
        enabled: false
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: -1ms
        shutdown-timeout: 200ms
        cluster:
          refresh:
            adaptive: true
            period: 30s

  firebase:
    config:
      path: ${FIREBASE_CONFIG_PATH:/etc/gcp/credentials/gcp-credentials.json}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: PLAINTEXT
      retry.backoff.ms: 1000
      request.timeout.ms: 30000
      max.block.ms: 30000
    producer:
      acks: 1
      retries: 3
    consumer:
      auto-offset-reset: latest
      group-id: ${spring.application.name}
    admin:
      fail-fast: false

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}
    metadata-map:
      user.name: ${eureka.client.security.user.name:craftpilot}
      user.password: ${eureka.client.security.user.password:13579ada}
  client:
    serviceUrl:
      defaultZone: http://${eureka.client.security.user.name:craftpilot}:${eureka.client.security.user.password:13579ada}@${EUREKA_HOST:eureka-server}:${EUREKA_PORT:8761}/eureka/
    register-with-eureka: ${EUREKA_REGISTER:true}
    fetch-registry: ${EUREKA_FETCH:true}
    enabled: ${EUREKA_ENABLED:true}
    healthcheck:
      enabled: true
    refresh:
      enable: true
    shouldDisableDelta: true
    registry-fetch-interval-seconds: 30
    security:
      user:
        name: ${EUREKA_USERNAME:craftpilot}
        password: ${EUREKA_PASSWORD:13579ada}

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: redis,diskSpace
          show-details: always
        liveness:
          include: ping
          show-details: always
  health:
    redis:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
    diskspace:
      enabled: true
    circuitbreakers:
      enabled: true
    kafka:
      enabled: false # Disable Kafka health check temporarily

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    instances:
      userPreferences:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

kafka:
  topics:
    user-events: user-events
    user-activity: user-activity

logging:
  level:
    root: INFO
    com.craftpilot.userservice: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.boot.actuate: DEBUG
