spring:
  application:
    name: user-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
    include: kafka-base
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      connect-timeout: 2000
      timeout: 1000

  firebase:
    config:
      path: ${FIREBASE_CONFIG_PATH:/etc/gcp/credentials/gcp-credentials.json}

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    register-with-eureka: true
    fetch-registry: true

server:
  port: ${SERVER_PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus,info,loggers
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: redis,diskSpace
          show-details: always
        liveness:
          include: ping
          show-details: always
  health:
    redis:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    instances:
      userPreferences:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

kafka:
  topics:
    user-events: user-events
    user-activity: user-activity

logging:
  level:
    root: INFO
    com.craftpilot.userservice: DEBUG
    org.springframework.data.redis: DEBUG
    org.springframework.boot.actuate: DEBUG
