spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      retries: 1
      acks: 1
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        # Güvenlik için idempotence devre dışı bırakıldı - daha az sistem yükü
        enable.idempotence: false
        max.block.ms: 3000
        request.timeout.ms: 3000
        delivery.timeout.ms: 5000
        linger.ms: 10
    consumer:
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.craftpilot.*"
        max.poll.records: 100
        heartbeat.interval.ms: 3000
        session.timeout.ms: 30000
        fetch.max.wait.ms: 500
    admin:
      auto-create: true
      fail-fast: false

kafka:
  topic:
    partitions: 3
    replicas: 1
