server:
  port: 8063
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
  shutdown: graceful

spring:
  application:
    name: admin-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
    include: kafka-base
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://craftpilot:secure_password@craftpilot-mongodb:27017/craftpilot?authSource=admin&retryWrites=true&w=majority&serverSelectionTimeoutMS=60000}
      database: ${SPRING_DATA_MONGODB_DATABASE:craftpilot}
      auto-index-creation: true
      connect-timeout: 60000
      socket-timeout: 60000
      max-wait-time: 120000
      max-connection-idle-time: 300000
      max-connection-life-time: 600000
      # MongoDB health ve bağlantı dayanıklılığı ayarları
      retry-writes: true
      max-connection-pool-size: 20
      min-connection-pool-size: 5
      max-connection-life-time: 30000
      server-selection-timeout: 60000
      maintenance-frequency: 20000
      maintenance-initial-delay: 5000
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:13579ada}
      timeout: 10000
      connect-timeout: 10000
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: mongo,redis,diskSpace
        liveness:
          include: ping
  health:
    mongodb:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
