server:
  port: 8063
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
  shutdown: graceful

spring:
  application:
    name: admin-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
    include: kafka-base
  data:
    mongodb:
      # MongoDB yapılandırması - sadeleştirilmiş
      uri: ${MONGODB_URI:mongodb://${MONGO_ROOT_USERNAME:craftpilot}:${MONGO_ROOT_PASSWORD:secure_password}@${MONGODB_HOST:craftpilot-mongodb}:27017/${MONGODB_DATABASE:craftpilot_admin_db}?authSource=admin&retryWrites=true&w=majority}
      database: ${MONGODB_DATABASE:craftpilot_admin_db}
      auto-index-creation: false # Otomatik index oluşturma kapalı
      # Temel bağlantı parametreleri
      connect-timeout: 30000
      socket-timeout: 60000
      max-wait-time: 60000
      max-connection-pool-size: 20
      min-connection-pool-size: 5
      server-selection-timeout: 30000
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:13579ada}
      timeout: 10000
      connect-timeout: 10000
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: mongo,redis,diskSpace
        liveness:
          include: ping
  health:
    mongodb:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  level:
    com.netflix.discovery.shared.resolver.aws.ConfigClusterResolver: WARN
# Özel mongodb indeks yapılandırması kaldırıldı
