server:
  port: 8063
  ssl:
    enabled: false

spring:
  profiles:
    active: local
  application:
    name: admin-service
  cloud:
    gcp:
      credentials:
        location: file:/opt/craftpilot/gcp-credentials.json
      firestore:
        enabled: true
        project-id: ${GCP_PROJECT_ID}
        credentials:
          location: file:/opt/craftpilot/gcp-credentials.json
    kubernetes:
      enabled: false
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: admin-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

logging:
  level:
    com.craftpilot.adminservice: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
  show-actuator: true

resilience4j:
  ratelimiter:
    instances:
      adminApi:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 500ms

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://securetoken.google.com/${GCP_PROJECT_ID}
        jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com
