server:
  port: 8063

spring:
  application:
    name: admin-service
  cloud:
    gcp:
      credentials:
        location: file:/app/gcp-credentials.json
      firestore:
        project-id: ${GCP_PROJECT_ID:craft-pilot-ai}
    kubernetes:
      enabled: false
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:eureka}:${EUREKA_PASSWORD:secret}@eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
