server:
  port: 8063

spring:
  application:
    name: admin-service
  cloud:
    gcp:
      credentials:
        location: file:/opt/craftpilot/gcp-credentials.json
      firestore:
        enabled: true
        project-id: ${GCP_PROJECT_ID}
        credentials:
          location: file:/opt/craftpilot/gcp-credentials.json
    kubernetes:
      enabled: false
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: admin-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: https://securetoken.google.com/${GCP_PROJECT_ID}
        jwk-set-uri: https://www.googleapis.com/robot/v1/metadata/jwk/securetoken@system.gserviceaccount.com
