server:
  port: 8063

spring:
  application:
    name: admin-service
  cloud:
    gcp:
      credentials:
        location: file:/app/gcp-credentials.json
      firestore:
        project-id: ${GCP_PROJECT_ID:craft-pilot-ai}
    kubernetes:
      enabled: false
    discovery:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USERNAME:craftpilot}:${EUREKA_PASSWORD:13579ada}@eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true
    hostname: admin-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
