server:
  port: 8081
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
  shutdown: graceful

spring:
  application:
    name: admin-service
  cloud:
    gcp:
      credentials:
        location: file:${GCP_SA_KEY}
      project-id: ${GCP_PROJECT_ID}
      firestore:
        project-id: ${GCP_PROJECT_ID:craft-pilot-ai}
        enabled: true
    discovery:
      enabled: true
    loadbalancer:
      ribbon:
        enabled: false
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:13579ada}
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms
        shutdown-timeout: 200ms

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://craftpilot:13579ada@eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:admin-service}
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    metadata-map:
      startup: ${random.int}
      user.name: ${spring.security.user.name}
      user.password: ${spring.security.user.password}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: redis,diskSpace
        liveness:
          include: ping
  health:
    redis:
      enabled: true
    circuitbreakers:
      enabled: true
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    validate-group-membership: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.craftpilot: DEBUG
    org.springframework.web: INFO
    org.springframework.data.redis: INFO
    org.springframework.cloud: INFO
