apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: craftpilot
  labels:
    app: analytics-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: analytics-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: analytics-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8064"
    spec:
      containers:
        - name: analytics-service
          image: craftpilot/analytics-service:latest
          ports:
            - containerPort: 8064
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: EUREKA_SERVER_URL
              value: "http://eureka-server.craftpilot.svc.cluster.local:8761/eureka/"
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: gcp-credentials
                  key: project-id
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/gcp/credentials.json"
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: bootstrap-servers
          volumeMounts:
            - name: gcp-credentials
              mountPath: "/etc/gcp"
              readOnly: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8064
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8064
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
            items:
              - key: credentials.json
                path: credentials.json
---
apiVersion: v1
kind: Service
metadata:
  name: analytics-service
spec:
  selector:
    app: analytics-service
  ports:
    - port: 80
      targetPort: 8064
  type: ClusterIP
