apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: analytics-service-monitor
  namespace: craftpilot
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: analytics-service
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
  namespaceSelector:
    matchNames:
      - craftpilot
