server:
  port: 8066
  compression:
    enabled: true
    mime-types: text/event-stream,application/json,text/plain
    min-response-size: 1024
  shutdown: graceful
  netty:
    connection-timeout: 60000 # 1 dakika (daha makul bir değer)
    idle-timeout: 60000 # 1 dakika
    max-keep-alive-requests: 1000 # Daha makul bir değer
    threads:
      worker: 4
      boss: 1
    validate-headers: true
    max-connections: 10000
    max-initial-line-length: 8192
    max-header-size: 16384
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false
  http2:
    enabled: true

spring:
  application:
    name: llm-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
    # Kafka profilini varsayılan olarak aktif et
    include: kafka-base
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
    # Kafka olmazsa hata vermemesi için ekleyin
    allow-circular-references: true
  codec:
    max-in-memory-size: 16MB
  # Redis ayarları
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:13579ada}
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms
    mongodb:
      uri: ${MONGODB_URI:mongodb://${MONGO_ROOT_USERNAME:craftpilot}:${MONGO_ROOT_PASSWORD:secure_password}@${MONGODB_HOST:craftpilot-mongodb}:27017/${MONGODB_DATABASE:craftpilot_llm_db}?authSource=admin&retryWrites=true&w=majority&serverSelectionTimeoutMS=30000&connectTimeoutMS=20000&socketTimeoutMS=60000}
      database: ${MONGODB_DATABASE:craftpilot_llm_db}
      auto-index-creation: ${MONGODB_AUTO_INDEX_CREATION:false}
      # Gelişmiş bağlantı parametreleri
      connect-timeout: 30000
      socket-timeout: 60000
      max-wait-time: 120000
      max-connection-idle-time: 300000
      max-connection-life-time: 600000
      # MongoDB dayanıklılık ayarları
      retry-writes: true
      max-connection-pool-size: 20
      min-connection-pool-size: 5
      server-selection-timeout: 60000
  # Cache ayarları
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
      use-key-prefix: true
  # Kafka yapılandırmasını ekleyelim/düzenleyelim
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    producer:
      retries: 3
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

# WebClient yapılandırması
webclient:
  timeout: 30000
  max-in-memory-size: 10485760
  connection:
    max-connections: 50
    acquire-timeout: 15
    max-idle-time: 30
    max-life-time: 300
    eviction-interval: 120

# Kullanıcı bellek servisi yapılandırması
user-memory:
  service:
    url: ${USER_MEMORY_SERVICE_URL:http://user-memory-service:8067}
    # Kubernetes veya Docker Compose ortamında servis adı kullanılır
    # Lokal geliştirme için localhost:8067 olarak değiştirilebilir
  non-meaningful-strings: >
    Kullanıcı mesaj gönderdi,
    Mesajdan bilgi çıkarılamadı,
    Kullanıcıdan bilgi çıkarılamadı,
    NO_INFORMATION,
    EXTRACTION_ERROR,
    PARSING_ERROR,
    INVALID_RESPONSE_FORMAT

# Activity logging yapılandırması
activity:
  service-name-prefix: LLM
  kafka-topic: activity-events

# Eureka ayarları
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://craftpilot:13579ada@eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:llm-service}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /health
    status-page-url-path: /actuator/info
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
    instance-id: ${spring.application.name}:${server.port}:${random.uuid}

# Actuator ayarları
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: "*"
        liveness:
          include: ping,diskSpace
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    mongodb:
      enabled: true

# OpenRouter API ayarları
openrouter:
  api:
    key: ${OPENROUTER_API_KEY}
    url: https://openrouter.ai/api/v1
    defaultModel: google/gemini-2.0-flash-lite-001
    maxTokens: 2000
    temperature: 0.7
    retryAttempts: 3
    retryDelay: 1000
    http-referer: https://craftpilot.io
  requestTimeoutSeconds: 60
  streamTimeoutSeconds: 120
  keepAliveIntervalSeconds: 5
  defaultModel: google/gemini-2.0-flash-lite-001

# Logging ayarları - Temizlenmiş ve basitleştirilmiş
# Detaylı logger yapılandırmaları logback-spring.xml'e taşındı
logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.craftpilot: DEBUG
    org.springframework.web: INFO

resilience4j:
  circuitbreaker:
    instances:
      llmService:
        slidingWindowSize: 50
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      openRouterApiCircuit:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        registerHealthIndicator: true
        recordExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - com.craftpilot.llmservice.exception.APIException
      userMemoryService:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        recordExceptions:
          - org.springframework.web.reactive.function.client.WebClientResponseException
          - java.util.concurrent.TimeoutException
          - java.io.IOException

  ratelimiter:
    instances:
      llmService:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
  retry:
    instances:
      openRouterApiCircuit:
        maxRetryAttempts: 3
        waitDuration: 500ms
        retryExceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.reactive.function.client.WebClientResponseException
      userMemoryService:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2

lighthouse:
  service:
    url: ${LIGHTHOUSE_SERVICE_URL:http://lighthouse-service:8085}

ai:
  model:
    extraction: anthropic/claude-3-haiku

# Extraksiyon ayarları
extraction:
  timeout:
    seconds: 30
  memory:
    timeout:
      seconds: 15
  retry:
    max: 3
    backoff:
      ms: 500

memory:
  timeout:
    seconds: 10

user-info-extraction:
  debug: true
  save-all-messages: false

# MongoDB özel ayarlar
mongodb:
  create-indexes: ${MONGODB_CREATE_INDEXES:false}
  metrics:
    enabled: ${MONGODB_METRICS_ENABLED:true}
