server:
  port: 8062
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
  shutdown: graceful
  netty:
    connection-timeout: 5000
    idle-timeout: 15000
    max-keep-alive-requests: 1000
    threads:
      worker: 4
      boss: 1

spring:
  application:
    name: llm-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  main:
    web-application-type: reactive
  webflux:
    base-path: /
  codec:
    max-in-memory-size: 16MB
  reactor:
    netty:
      client:
        protocols: http11
        maxConnections: 500
        maxIdleTime: 20s
        maxLifeTime: 60s
      pool:
        type: elastic
        max-connections: 500
        maxIdleTime: 20s
        maxLifeTime: 60s
        leasingStrategy: fifo
      resources:
        loop-resources:
          preferred-native-transport: false
  cloud:
    discovery:
      enabled: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:13579ada}
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://craftpilot:13579ada@eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

openrouter:
  api:
    key: ${OPENROUTER_API_KEY}
    url: https://openrouter.ai/api/v1
    defaultModel: google/gemini-2.0-flash-lite-preview-02-05:free
    maxTokens: 2000
    temperature: 0.7
    retryAttempts: 3
    retryDelay: 1000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.craftpilot: DEBUG
    org.springframework.web: INFO
    org.springframework.cloud: INFO
    reactor.netty: DEBUG
    io.netty: DEBUG
