server:
  port: 8062
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
  shutdown: graceful
  netty:
    connection-timeout: 5000
    idle-timeout: 30000
    max-keep-alive-requests: 10000
    threads:
      worker: 8 # CPU çekirdek sayısı x 2
      boss: 2 # CPU çekirdek sayısı / 2
    validate-headers: true
    max-connections: 10000
    max-initial-line-length: 8192
    max-header-size: 16384
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: llm-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  webflux:
    base-path: /
    format:
      date: yyyy-MM-dd
      date-time: yyyy-MM-dd HH:mm:ss
    log-request-details: false # Production'da false olmalı
    connection:
      pool:
        maxIdleTime: 15m
        maxLifeTime: 1h
        maxSize: 1000
        pendingAcquireMaxCount: 2000
        pendingAcquireTimeout: 2s
  codec:
    max-in-memory-size: 16MB
  kafka:
    properties:
      security.protocol: PLAINTEXT
      reconnect.backoff.ms: 1000
      reconnect.backoff.max.ms: 5000
    consumer:
      auto-offset-reset: earliest
      group-id: llm-service-group
    producer:
      retries: 3
      acks: all
  cloud:
    discovery:
      enabled: true
    circuitbreaker:
      resilience4j:
        enabled: true
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:13579ada}
      timeout: 5000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 1000ms
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
      use-key-prefix: true
      key-prefix: "llm:" # Cache key prefix eklendi
  reactor:
    netty:
      pool:
        type: fixed # 'elastic' yerine 'fixed' kullanıyoruz
        maxConnections: 500 # Eş zamanlı maksimum bağlantı sayısı
        pendingAcquireTimeout: 5000 # Bağlantı alma zaman aşımı (ms)
        evictInBackground: 120000 # Arka planda temizleme süresi (ms)
        metrics: true # Metrics aktif
  security:
    basic:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://craftpilot:13579ada@eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ${HOSTNAME:llm-service}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

openrouter:
  api:
    key: ${OPENROUTER_API_KEY}
    url: https://openrouter.ai/api/v1
    defaultModel: google/gemini-2.0-flash-lite-preview-02-05:free
    maxTokens: 2000
    temperature: 0.7
    retryAttempts: 3
    retryDelay: 1000
    http-referer: https://craftpilot.io

kafka:
  topics:
    ai-events: ai-events
    llm-completions: llm-completions
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  consumer:
    group-id: llm-service-group
    auto-offset-reset: earliest
  producer:
    retries: 3
    acks: all
    properties:
      max.block.ms: 5000
      request.timeout.ms: 2000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId}] %-5level %logger{36} - %msg%n"
  level:
    root: WARN # Default log seviyesi WARN
    com.craftpilot: INFO # Uygulama logları INFO
    org.springframework: WARN
    reactor.netty: WARN
    io.netty: WARN
    reactor.netty.http.client: WARN
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.cache: WARN
    org.springframework.data: WARN
    io.micrometer: WARN

netty:
  native:
    enabled: false
  io:
    noNative: true
    noUnsafe: true
  use-native-transport: true
  workdir: /tmp/netty

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    configUrl: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: LLM API
  api-docs:
    path: /v3/api-docs
    enabled: true
  show-actuator: true
  packages-to-scan: com.craftpilot.llmservice.controller
  paths-to-match: /ai/**

# CORS Yapılandırması
cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
  allow-credentials: true
  max-age: 3600

resilience4j:
  circuitbreaker:
    instances:
      llmService:
        slidingWindowSize: 100
        failureRateThreshold: 50
        waitDurationInOpenState: 20s
        permittedNumberOfCallsInHalfOpenState: 10
      openRouter:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10
  ratelimiter:
    instances:
      llmService:
        limitForPeriod: 100
        limitRefreshPeriod: 1s
        timeoutDuration: 5s
  bulkhead:
    instances:
      llmService:
        maxConcurrentCalls: 50

security:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:*}
