apiVersion: v1
kind: ConfigMap
metadata:
  name: subscription-service-config
  namespace: craftpilot
data:
  application.yml: |
    server:
      port: 8085

    spring:
      application:
        name: subscription-service
      cache:
        type: redis
      kafka:
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      data:
        redis:
          repositories:
            enabled: false
      cloud:
        kubernetes:
          discovery:
            enabled: true
        service-registry:
          auto-registration:
            enabled: true

    eureka:
      instance:
        preferIpAddress: true
        leaseRenewalIntervalInSeconds: 10
        health-check-url-path: /actuator/health
        instanceId: ${spring.application.name}:${spring.cloud.client.hostname}:${server.port}
        statusPageUrlPath: /actuator/info
        healthCheckUrlPath: /actuator/health
      client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
          defaultZone: ${EUREKA_SERVER_URL:http://eureka-server:8761}/eureka/
        username: ${EUREKA_USERNAME:craftpilot}
        password: ${EUREKA_PASSWORD:13579ada}

    management:
      endpoints:
        web:
          base-path: /actuator
          exposure:
            include: "*"
      endpoint:
        health:
          show-details: always
          probes:
            enabled: true
      health:
        livenessState:
          enabled: true
        readinessState:
          enabled: true

    logging:
      level:
        com.craftpilot.subscriptionservice: INFO
        org.springframework.data: INFO
        org.springframework.security: INFO

    resilience4j:
      circuitbreaker:
        instances:
          subscriptionService:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 5
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
      ratelimiter:
        instances:
          subscriptionService:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 3s

    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
