apiVersion: v1
kind: ConfigMap
metadata:
  name: subscription-service-config
  namespace: craftpilot
data:
  application.yml: |
    server:
      port: 8085

    spring:
      application:
        name: subscription-service
      cache:
        type: redis
      kafka:
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      data:
        redis:
          repositories:
            enabled: false

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
        metrics:
          enabled: true
        prometheus:
          enabled: true

    logging:
      level:
        com.craftpilot.subscriptionservice: INFO
        org.springframework.data: INFO
        org.springframework.security: INFO

    resilience4j:
      circuitbreaker:
        instances:
          subscriptionService:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 5
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
      ratelimiter:
        instances:
          subscriptionService:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 3s

    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
