apiVersion: v1
kind: Secret
metadata:
  name: eureka-credentials
  namespace: craftpilot
type: Opaque
data:
  username: Y3JhZnRwaWxvdA==  # Base64 encoded value of 'craftpilot'
  password: MTM1NzlhZGE=      # Base64 encoded value of '13579ada'
