apiVersion: v1
kind: Service
metadata:
  name: subscription-service
  namespace: craftpilot
  labels:
    app: subscription-service
spec:
  type: ClusterIP
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    app: subscription-service
