server:
  port: 8095
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
  shutdown: graceful

spring:
  application:
    name: activity-log-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
    include: kafka-base
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://${MONGO_ROOT_USERNAME:craftpilot}:${MONGO_ROOT_PASSWORD:secure_password}@${MONGODB_HOST:craftpilot-mongodb}:27017/${MONGO_INITDB_DATABASE:craftpilot}?authSource=admin&retryWrites=true&w=majority&serverSelectionTimeoutMS=30000&connectTimeoutMS=20000&socketTimeoutMS=60000}
      database: ${MONGODB_DATABASE:craftpilot}
      connection-timeout: 30000
      socket-timeout: 60000
      max-connection-idle-time: 300000
      connection-pool-max-size: 20
      auto-index-creation: true
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: activity-log-service
      auto-offset-reset: latest
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.craftpilot.commons.activity.model,com.craftpilot.activitylogservice.model
        spring.json.value.default.type: com.craftpilot.commons.activity.model.ActivityEvent
        spring.json.use.type.headers: false

# Redis yapılandırması
spring.data.redis:
  host: ${REDIS_HOST:redis}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:13579ada}
  timeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: mongo,redis,diskSpace
        liveness:
          include: ping
    metrics:
      enabled: true
    prometheus:
      enabled: true
  health:
    mongodb:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.craftpilot: DEBUG
    org.springframework.web: INFO
    org.springframework.kafka: INFO
    org.springframework.data.mongodb: INFO
    com.craftpilot.activitylogservice: INFO
    org.apache.kafka: WARN

kafka:
  topics:
    activity-events: ${ACTIVITY_KAFKA_CONSUMER_TOPIC:activity-events}
  consumer:
    group-id: ${spring.application.name}-group
    concurrency: 3
    auto-offset-reset: earliest
    max-poll-records: 100

pagination:
  default-page-size: 20
  max-page-size: 100

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://craftpilot:13579ada@eureka-server:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
    instance-info-replication-interval-seconds: 10
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:activity-log-service}
    lease-renewal-interval-in-seconds: 10
    health-check-url-path: /actuator/health
    status-page-url-path: /actuator/info
    home-page-url: http://${eureka.instance.hostname}:${server.port}/
    instance-id: ${spring.application.name}:${server.port}:${random.uuid}
    metadata-map:
      management:
        context-path: /actuator

activity:
  kafka:
    consumer:
      topic: ${ACTIVITY_KAFKA_CONSUMER_TOPIC:activity-events}
    retry:
      max-attempts: 3
      initial-backoff: 1000
