server:
  port: 8064
  compression:
    enabled: true
    mime-types: application/json,text/plain
    min-response-size: 1024
  shutdown: graceful

spring:
  application:
    name: analytics-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:prod}
    include: ${KAFKA_ENABLED:true} ? kafka-base
  cloud:
    discovery:
      enabled: true
  main:
    web-application-type: reactive
    fail-fast: false
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://craftpilot:secure_password@mongodb:27017/analytics?authSource=admin&retryWrites=true&w=majority}
      auto-index-creation: true
      connection-timeout: 30000
      socket-timeout: 60000
      max-connection-idle-time: 300000
      retry-writes: true
      retry-reads: true

# Kafka topic yapılandırması
kafka:
  topics:
    analytics-events: analytics-events
    metrics-events: metrics-events
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  enabled: ${KAFKA_ENABLED:true}
  admin:
    fail-fast: false
    auto-create: true
    bootstrap-timeout: 10000
    operations-timeout: 10000
    close-timeout: 5000

# Add MongoDB resilience configuration
mongodb:
  connection:
    retry:
      max-attempts: 10
      initial-interval: 1000
      max-interval: 30000
      multiplier: 2.0
  indexes:
    creation:
      enabled: ${MONGODB_INDEX_CREATION_ENABLED:true}
      startup-fail-fast: false

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://craftpilot:13579ada@eureka-server:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    hostname: ${HOSTNAME:analytics-service}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
  api-docs:
    path: /v3/api-docs
    enabled: true

redis:
  host: ${REDIS_HOST:redis}
  port: ${REDIS_PORT:6379}
  password: ${REDIS_PASSWORD:13579ada}

openai:
  api-key: ${OPENAI_API_KEY}

resilience4j:
  circuitbreaker:
    instances:
      analyticsService:
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] [%X{traceId}] [%X{userId}] %-5level %logger{36} - %msg%n"
  level:
    com.craftpilot.analyticsservice: ${LOG_LEVEL:INFO}
    org.springframework.data.mongodb: INFO
