spring:
  application:
    name: lighthouse-service
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:13579ada}
      connect-timeout: 5000 # Bağlantı zaman aşımı
      timeout: 3000 # Komut zaman aşımı
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2
          max-wait: 2000ms
        shutdown-timeout: 500ms
        # Ekstra dayanıklılık ayarları
        client-name: lighthouse-service
        client-options:
          disconnect-timeout: 3000ms
          auto-reconnect: true
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25
        keep-alive: 60s
        allow-core-thread-timeout: true

server:
  port: ${PORT:8085}

lighthouse:
  queue:
    name: ${LIGHTHOUSE_QUEUE_NAME:lighthouse-jobs}
  results:
    prefix: ${LIGHTHOUSE_RESULTS_PREFIX:lighthouse-results:}
  redis:
    connection:
      max-attempts: 5
      retry-delay-ms: 3000
  job:
    timeout: ${LIGHTHOUSE_JOB_TIMEOUT:300} # 5 dakika
    # Ekstra zaman aşımı koruma mekanizması
    max-processing-time: ${LIGHTHOUSE_MAX_PROCESSING_TIME:600} # 10 dakika
  worker:
    count: ${LIGHTHOUSE_WORKER_COUNT:3} # Worker sayısı
    poll-interval: 1000 # Poll aralığı (ms)
    check-interval: 10000 # Worker kontrol aralığı (ms)
    restart-attempts: ${LIGHTHOUSE_WORKER_RESTART_ATTEMPTS:3} # Worker yeniden başlatma deneme sayısı
  cli:
    path: ${LIGHTHOUSE_CLI_PATH:lighthouse} # Lighthouse CLI yolu
    timeout: ${LIGHTHOUSE_CLI_TIMEOUT:300} # CLI işlem zaman aşımı (sn)
    # Lighthouse CLI için ek ayarlar
    enable-error-reporting: ${LIGHTHOUSE_ENABLE_ERROR_REPORTING:true} # Hata raporlamayı etkinleştir
    max-retries: ${LIGHTHOUSE_CLI_MAX_RETRIES:2} # Başarısızlık durumunda yeniden deneme sayısı
    retry-delay: ${LIGHTHOUSE_CLI_RETRY_DELAY:5000} # Yeniden denemeler arasındaki bekleme süresi (ms)
    # Lighthouse CLI çalıştırma stratejisi - doğrudan veya npx ile
    use-npx: ${LIGHTHOUSE_USE_NPX:true} # NPX kullanarak lighthouse çalıştır
  temp:
    dir: ${LIGHTHOUSE_TEMP_DIR:/tmp/lighthouse} # Geçici dosyalar için dizin
    cleanup: ${LIGHTHOUSE_TEMP_CLEANUP:true} # Geçici dosyaların temizlenmesi

logging:
  level:
    root: INFO
    com.craftpilot: DEBUG
    org.springframework.data.redis: DEBUG
    io.lettuce: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: redis,diskSpace
          show-details: always
        liveness:
          include: ping
          show-details: always
  health:
    redis:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
