spring:
  application:
    name: lighthouse-service
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:13579ada}
      connect-timeout: 2000
      timeout: 1000
  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25
        keep-alive: 60s
        allow-core-thread-timeout: true

server:
  port: ${PORT:8085}

lighthouse:
  queue:
    name: ${LIGHTHOUSE_QUEUE_NAME:lighthouse-jobs}
  results:
    prefix: ${LIGHTHOUSE_RESULTS_PREFIX:lighthouse-results:}
  redis:
    connection:
      max-attempts: 5
      retry-delay-ms: 3000
  job:
    timeout: ${LIGHTHOUSE_JOB_TIMEOUT:120} # 2 dakika (saniye olarak)
  worker:
    count: ${LIGHTHOUSE_WORKER_COUNT:3} # Worker thread sayısı
    poll-interval: ${LIGHTHOUSE_WORKER_POLL_INTERVAL:1000} # ms

logging:
  level:
    root: INFO
    com.craftpilot: DEBUG
    org.springframework.data.redis: DEBUG
    io.lettuce: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
      group:
        readiness:
          include: redis,diskSpace
          show-details: always
        liveness:
          include: ping
          show-details: always
  health:
    redis:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true
