apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: craftpilot
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
    - port: 8087
      targetPort: 8087
      protocol: TCP
      name: http
  selector:
    app: notification-service
