apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: craftpilot
  labels:
    app: notification-service
spec:
  type: ClusterIP
  ports:
    - port: 8053  # Port 8087'den 8053'e güncellendi
      targetPort: 8053
      protocol: TCP
      name: http
  selector:
    app: notification-service
