apiVersion: v1
kind: ConfigMap
metadata:
  name: credit-service-config
  namespace: craftpilot
data:
  application.yml: |
    server:
      port: 8086

    spring:
      application:
        name: credit-service
      cache:
        type: redis
      kafka:
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      data:
        redis:
          repositories:
            enabled: false
        mongodb:
          uri: ${MONGODB_URI:mongodb://craftpilot:secure_password@mongodb:27017/craftpilot?authSource=admin&retryWrites=true&w=majority}
          database: ${MONGODB_DATABASE:craftpilot}
          connection-timeout: 30000
          socket-timeout: 60000
          max-connection-idle-time: 300000
          connection-pool-max-size: 20
          auto-index-creation: true

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
        metrics:
          enabled: true
        prometheus:
          enabled: true

    logging:
      level:
        com.craftpilot.creditservice: INFO
        org.springframework.data: INFO
        org.springframework.security: INFO
        org.springframework.data.mongodb: INFO

    resilience4j:
      circuitbreaker:
        instances:
          creditService:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 5
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
      ratelimiter:
        instances:
          creditService:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 3s

    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
