apiVersion: apps/v1
kind: Deployment
metadata:
  name: credit-service
  namespace: craftpilot
  labels:
    app: credit-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: credit-service
  template:
    metadata:
      labels:
        app: credit-service
    spec:
      containers:
        - name: credit-service
          image: ${DOCKER_IMAGE}
          ports:
            - containerPort: 8058
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:9092"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://craftpilot:13579ada@eureka-server:8761/eureka/"
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8058
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8058
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
