apiVersion: v1
kind: Service
metadata:
  name: credit-service
  namespace: craftpilot
  labels:
    app: credit-service
spec:
  type: ClusterIP
  ports:
    - port: 8086
      targetPort: 8086
      protocol: TCP
      name: http
  selector:
    app: credit-service
