server:
  port: ${SERVER_PORT:8054}
  shutdown: graceful
  netty:
    connection-timeout: 2s
    idle-timeout: 15s
    max-keep-alive-requests: 100

spring:
  application:
    name: model-service
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      acks: 1
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      compression-type: snappy
      properties:
        spring.json.add.type.headers: false
        linger.ms: 5
    consumer:
      group-id: ${SPRING_KAFKA_CONSUMER_GROUP_ID:model-service-group}
      auto-offset-reset: ${SPRING_KAFKA_CONSUMER_AUTO_OFFSET_RESET:earliest}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.craftpilot.modelservice.model"
  cache:
    type: redis
    redis:
      time-to-live: 3600000
      cache-null-values: false
      use-key-prefix: true
      key-prefix: craftpilot
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:your_redis_password}
    timeout: 2000
    connect-timeout: 2000
    lettuce:
      pool:
        max-active: 16
        max-idle: 8
        min-idle: 4
        max-wait: 1000ms
      shutdown-timeout: 200ms
  webflux:
    base-path: /
  main:
    web-application-type: reactive
  codec:
    max-in-memory-size: 16MB
  cloud:
    gcp:
      project-id: craft-pilot-ai
      firestore:
        enabled: true
      credentials:
        location: classpath:firebase-service-account.json
    kubernetes:
      config:
        enabled: true
        name: model-service-config
      reload:
        enabled: true
        mode: polling
        period: 1000
      discovery:
        all-namespaces: false

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.craftpilot: ${LOGGING_LEVEL_COM_CRAFTPILOT:DEBUG}
    org.springframework.data.redis: INFO
    org.springframework.kafka: INFO
    com.google.cloud: INFO
    org.springframework.web: INFO
    org.springframework.data: INFO

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
    registry-fetch-interval-seconds: 5
    register-with-eureka: true
    fetch-registry: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      probes:
        enabled: ${MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED:true}
      show-details: always
      group:
        readiness:
          include: redis
      validate-group-membership: false
  health:
    livenessstate:
      enabled: ${MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED:true}
    readinessstate:
      enabled: ${MANAGEMENT_HEALTH_READINESSSTATE_ENABLED:true}
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      slo:
        http.server.requests: 50ms, 100ms, 200ms, 500ms
    export:
      prometheus:
        enabled: true

resilience4j:
  circuitbreaker:
    instances:
      default:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
  retry:
    instances:
      default:
        maxAttempts: 3
        waitDuration: 1s
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
  ratelimiter:
    instances:
      default:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 0
  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 100

model:
  storage:
    bucket-name: ${MODEL_STORAGE_BUCKET_NAME:craft-pilot-ai-models}
    base-path: models
  training:
    batch-size: 32
    epochs: 10
    learning-rate: 0.001
    validation-split: 0.2
  inference:
    max-batch-size: 16
    timeout-seconds: 30
    cache-ttl-minutes: 60

openai:
  api-key: ${OPENAI_API_KEY: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}
  model: ${OPENAI_MODEL:gpt-4-turbo-preview}
  max-tokens: ${OPENAI_MAX_TOKENS:4000}
  temperature: ${OPENAI_TEMPERATURE:0.7}

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Model Service API
  show-actuator: true
  packages-to-scan: com.craftpilot.modelservice.controller
  paths-to-match: /**
