apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-service-config
  namespace: craftpilot
data:
  application.yml: |
    server:
      port: 8081

    spring:
      application:
        name: admin-service

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus
      endpoint:
        health:
          show-details: always
        metrics:
          enabled: true
        prometheus:
          enabled: true

    logging:
      level:
        com.craftpilot.adminservice: INFO
        org.springframework.web: INFO
        org.springframework.data: INFO

    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
        tagsSorter: alpha
      show-actuator: true
