apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: craftpilot
  labels:
    app: admin-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: craftpilot/admin-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: gcp-credentials
                  key: project-id
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/gcp/credentials.json"
          volumeMounts:
            - name: gcp-credentials
              mountPath: "/etc/gcp"
              readOnly: true
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
            items:
              - key: credentials.json
                path: credentials.json
