apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-service
  namespace: craftpilot
  labels:
    app: admin-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-service
  template:
    metadata:
      labels:
        app: admin-service
    spec:
      containers:
        - name: admin-service
          image: craftpilot/admin-service:latest
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: craftpilot-config
                  key: eureka.client.serviceUrl.defaultZone
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: craftpilot-secrets
                  key: gcp-project-id
          volumeMounts:
            - name: firebase-credentials
              mountPath: "/app/config"
              readOnly: true
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 90
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      volumes:
        - name: firebase-credentials
          secret:
            secretName: firebase-credentials
            items:
              - key: credentials.json
                path: credentials.json
