apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
  namespace: craftpilot
data:
  application.yml: |
    server:
      port: 8060

    spring:
      application:
        name: user-service
      cache:
        type: redis
      kafka:
        producer:
          key-serializer: org.apache.kafka.common.serialization.StringSerializer
          value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      data:
        redis:
          repositories:
            enabled: false

    management:
      endpoints:
        web:
          exposure:
            include: health,info,metrics,prometheus,loggers
      endpoint:
        health:
          show-details: always
        metrics:
          enabled: true
        prometheus:
          enabled: true
      metrics:
        tags:
          application: ${spring.application.name}
        distribution:
          percentiles-histogram:
            http.server.requests: true
      tracing:
        sampling:
          probability: 1.0

    logging:
      file:
        path: /var/log/craftpilot
      level:
        com.craftpilot.userservice: INFO
        org.springframework.data: INFO
        org.springframework.security: INFO

    resilience4j:
      circuitbreaker:
        instances:
          userService:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 3
            slidingWindowType: COUNT_BASED
            minimumNumberOfCalls: 5
            waitDurationInOpenState: 50s
            failureRateThreshold: 50
            ignoreExceptions:
              - com.craftpilot.userservice.exception.NotFoundException
              - com.craftpilot.userservice.exception.ValidationException
      ratelimiter:
        instances:
          userService:
            limitForPeriod: 10
            limitRefreshPeriod: 1s
            timeoutDuration: 3s
      retry:
        instances:
          userService:
            maxAttempts: 3
            waitDuration: 1s
            retryExceptions:
              - org.springframework.web.client.ResourceAccessException
              - java.util.concurrent.TimeoutException
      bulkhead:
        instances:
          userService:
            maxConcurrentCalls: 20
            maxWaitDuration: 2s
      timelimiter:
        instances:
          userService:
            timeoutDuration: 5s
            cancelRunningFuture: true

    springdoc:
      api-docs:
        path: /api-docs
      swagger-ui:
        path: /swagger-ui.html
        operationsSorter: method
