apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: craftpilot
  labels:
    app: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: user-service
          image: craftpilot/user-service:latest
          ports:
            - containerPort: 8060
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-host
            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: redis-config
                  key: redis-port
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: kafka-config
                  key: bootstrap-servers
            - name: EUREKA_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: eureka-config
                  key: eureka-url
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/gcp/credentials/gcp-credentials.json"
            - name: FIREBASE_CONFIG_PATH
              value: "/etc/gcp/credentials/gcp-credentials.json"
          volumeMounts:
            - name: gcp-credentials
              mountPath: "/etc/gcp/credentials"
              readOnly: true
            - name: logs
              mountPath: "/app/logs"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1.5Gi" # Increased for better performance
              cpu: "750m" # Increased for better performance
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8060
            initialDelaySeconds: 90
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8060
            initialDelaySeconds: 45
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8060
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsUser: 1000
            runAsGroup: 1000
            capabilities:
              drop:
                - ALL
      volumes:
        - name: gcp-credentials
          secret:
            secretName: gcp-credentials
            defaultMode: 0400
            items:
              - key: credentials.json
                path: gcp-credentials.json
        - name: logs
          emptyDir: {}
