name: Activity Log Service CI/CD

on:
  push:
    branches: [master]
    paths:
      - "activity-log-service/**"
      - ".github/workflows/activity-log-service-ci-cd.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build with Maven (with verbose output)
        run: |
          cd activity-log-service
          mvn clean package -DskipTests -X

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          context: ./activity-log-service
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/activity-log-service:latest-arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/activity-log-service:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/activity-log-service:buildcache,mode=max

      - name: Verify Docker build status
        run: |
          echo "Docker build and push completed with digest ${{ steps.docker_build.outputs.digest }}"
          if [ -z "${{ steps.docker_build.outputs.digest }}" ]; then
            echo "Docker build failed to produce a digest output"
            exit 1
          fi

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true
          script: |
            echo "Starting deployment of Activity Log Service..."
            # Deploy Activity Log Service
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/activity-log-service:latest-arm64
            docker stop activity-log-service || true
            docker rm activity-log-service || true

            # Geliştirilmiş ortam değişkenleri ve network ayarları
            docker run -d \
              --name activity-log-service \
              --network craftpilot-network \
              --restart unless-stopped \
              -p 8095:8095 \
              -v /opt/craftpilot/gcp-credentials.json:/gcp-credentials.json:ro \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e KAFKA_BOOTSTRAP_SERVERS=kafka:9092 \
              -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://craftpilot:13579ada@eureka-server:8761/eureka/ \
              -e HOSTNAME=activity-log-service \
              -e GOOGLE_APPLICATION_CREDENTIALS=/gcp-credentials.json \
              -e SPRING_SECURITY_USER_NAME=craftpilot \
              -e SPRING_SECURITY_USER_PASSWORD=13579ada \
              -e SPRING_CLOUD_GCP_PROJECT_ID=craft-pilot-ai \
              -e REDIS_HOST=redis \
              -e REDIS_PORT=6379 \
              -e REDIS_PASSWORD=13579ada \
              -e MANAGEMENT_HEALTH_VALIDATE_GROUP_MEMBERSHIP=false \
              ${{ secrets.DOCKERHUB_USERNAME }}/activity-log-service:latest-arm64

            # Geliştirilmiş sağlık kontrolü - başlangıç gecikmesi eklendi
            echo "Waiting for service to start..."
            sleep 15
            for i in {1..12}; do
              if curl -s http://localhost:8095/actuator/health | grep -q "UP"; then
                echo "Service is healthy"
                exit 0
              fi
              echo "Attempt $i: Service not ready yet..."
              sleep 10
            done

            echo "Service failed to become healthy within timeout"
            docker logs activity-log-service
            exit 1
