name: Admin Service CI/CD

on:
  push:
    paths:
      - "admin-service/**"
      - ".github/workflows/admin-service-ci-cd.yml"
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "corretto"

      - name: Create GCP Credentials Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p /opt/craftpilot

      - name: Build with Maven
        run: |
          cd admin-service
          mvn clean package -DskipTests

      - name: Build and Push Docker Image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd admin-service
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t $DOCKER_USERNAME/admin-service:latest .
          docker push $DOCKER_USERNAME/admin-service:latest

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          envs: DOCKER_USERNAME,GCP_PROJECT_ID
          script: |
            # GCP kimlik bilgilerini oluştur
            mkdir -p /opt/craftpilot
            echo '${{ secrets.GCP_SA_KEY }}' > /opt/craftpilot/gcp-credentials.json
            chmod 600 /opt/craftpilot/gcp-credentials.json

            # Docker container'ı güncelle
            docker pull ${{ secrets.DOCKER_USERNAME }}/admin-service:latest
            docker stop admin-service || true
            docker rm admin-service || true
            docker run -d \
              --name admin-service \
              --network craftpilot-network \
              -p 8063:8063 \
              -e GCP_PROJECT_ID=$GCP_PROJECT_ID \
              -v /opt/craftpilot/gcp-credentials.json:/opt/craftpilot/gcp-credentials.json:ro \
              ${{ secrets.DOCKER_USERNAME }}/admin-service:latest
