name: Admin Service CI/CD

on:
  push:
    branches: [master]
    paths:
      - "admin-service/**"
      - ".github/workflows/admin-service-ci-cd.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./admin-service
    steps:
      - uses: actions/checkout@v3

      # QEMU kurulumu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      # Docker Buildx kurulumu
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      # Docker Hub'a giriş yap
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      # Sadece ARM64 için build ve push
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./admin-service
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/admin-service:latest-arm64
            ${{ secrets.DOCKERHUB_USERNAME }}/admin-service:${{ github.sha }}-arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/admin-service:buildcache-arm64
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/admin-service:buildcache-arm64,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GCP_SA_KEY
          script: |
            echo "=== Creating GCP Credentials ==="
            mkdir -p /opt/craftpilot
            echo "$GCP_SA_KEY" > /opt/craftpilot/gcp-credentials.json
            chmod 600 /opt/craftpilot/gcp-credentials.json

            echo "=== Pulling ARM64 Image ==="
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/admin-service:latest-arm64

            echo "=== Stopping Old Container ==="
            docker stop admin-service || true
            docker rm admin-service || true

            echo "=== Starting New Container ==="
            docker run -d \
              --name admin-service \
              --network craftpilot-network \
              -p 8063:8063 \
              -v /opt/craftpilot/gcp-credentials.json:/app/gcp-credentials.json:ro \
              -e GOOGLE_APPLICATION_CREDENTIALS=/app/gcp-credentials.json \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SPRING_CLOUD_GCP_CREDENTIALS_LOCATION=file:/app/gcp-credentials.json \
              -e GCP_PROJECT_ID=craft-pilot-ai \
              -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/ \
              -e EUREKA_INSTANCE_PREFERIPADDRESS=true \
              -e EUREKA_USERNAME=craftpilot \
              -e EUREKA_PASSWORD=13579ada \
              ${{ secrets.DOCKERHUB_USERNAME }}/admin-service:latest-arm64

            echo "=== Waiting for Container to Start ==="
            sleep 30

            echo "=== Health Check ==="
            for i in {1..5}; do
              if curl -f http://localhost:8063/actuator/health; then
                echo "Service is healthy"
                exit 0
              fi
              echo "Attempt $i: Waiting for service to start..."
              sleep 10
            done

            echo "Service failed health check"
            docker logs admin-service
            exit 1

      - name: Trigger Deploy Services Workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: trigger-deploy-services
