name: API Gateway CI/CD

on:
  push:
    branches: [master]
    paths:
      - "api-gateway/**"
      - ".github/workflows/api-gateway-ci-cd.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Grant execute permission for mvnw
        run: |
          cd api-gateway
          chmod +x mvnw

      - name: Build
        run: |
          cd api-gateway
          ./mvnw clean package -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./api-gateway
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest-arm64

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Infrastructure setup
            echo "=== Setting up infrastructure ==="
            docker network create craftpilot-network || true

            # Start Redis if not running
            if ! docker ps | grep -q redis; then
              docker run -d \
                --name redis \
                --network craftpilot-network \
                -p 6379:6379 \
                -e REDIS_PASSWORD=13579ada \
                redis:latest --requirepass 13579ada
            fi

            # Deploy API Gateway
            echo "=== Deploying API Gateway ==="
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest-arm64
            docker stop api-gateway || true
            docker rm api-gateway || true

            docker run -d \
              --name api-gateway \
              --hostname api-gateway \
              --network craftpilot-network \
              --restart unless-stopped \
              -p 8080:8080 \
              -v /opt/craftpilot/gcp-credentials.json:/app/config/gcp-credentials.json:ro \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SERVER_PORT=8080 \
              -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://craftpilot:13579ada@eureka-server:8761/eureka/ \
              -e EUREKA_INSTANCE_HOSTNAME=api-gateway \
              -e EUREKA_INSTANCE_PREFER_IP_ADDRESS=false \
              -e MANAGEMENT_HEALTH_VALIDATE_GROUP_MEMBERSHIP=false \
              -e SPRING_CLOUD_CONFIG_ENABLED=false \
              -e SPRING_SECURITY_BASIC_ENABLED=false \
              -e MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info \
              -e MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always \
              -e SPRING_APPLICATION_NAME=api-gateway \
              -e GOOGLE_APPLICATION_CREDENTIALS=/app/config/gcp-credentials.json \
              -e REDIS_HOST=redis \
              -e REDIS_PORT=6379 \
              -e REDIS_PASSWORD=13579ada \
              ${{ secrets.DOCKERHUB_USERNAME }}/api-gateway:latest-arm64

            echo "=== Waiting for initial startup ==="
            sleep 15  # İlk başlangıç için biraz daha uzun bekleme süresi

            echo "=== Performing health checks ==="
            max_retries=30
            counter=0

            until [ $counter -ge $max_retries ]
            do
              echo "Health check attempt $((counter + 1))/$max_retries"
              
              # Konteyner çalışıyor mu?
              if ! docker ps --format '{{.Status}}' -f name=api-gateway | grep -q "Up"; then
                echo "Container is not running properly"
                docker logs api-gateway --tail 50
                sleep 10
                counter=$((counter + 1))
                continue
              fi
              
              # Spring Boot başlangıç kontrolü
              if ! docker logs api-gateway 2>&1 | grep -q "Started ApiGatewayApplication"; then
                echo "Application not fully started yet..."
                sleep 10
                counter=$((counter + 1))
                continue
              fi
              
              # HTTP endpoint kontrolü
              HEALTH_CHECK=$(curl -s -w "%{http_code}" http://localhost:8080/actuator/health -o /dev/null)
              if [ "$HEALTH_CHECK" = "200" ]; then
                echo "✓ Health endpoint is responding"
                
                # Detaylı sağlık kontrolü
                HEALTH_STATUS=$(curl -s http://localhost:8080/actuator/health | grep -o '"status":"[^"]*' | cut -d'"' -f4)
                if [ "$HEALTH_STATUS" = "UP" ]; then
                  echo "✓ Application is healthy and running"
                  
                  # Eureka kayıt kontrolü
                  if curl -s http://craftpilot:13579ada@localhost:8761/eureka/apps/API-GATEWAY | grep -q "API-GATEWAY"; then
                    echo "✓ Successfully registered with Eureka"
                    echo "=== Deployment completed successfully ==="
                    exit 0
                  fi
                fi
              fi
              
              echo "Waiting for next health check..."
              sleep 10
              counter=$((counter + 1))
            done

            echo "=== Health Check Failed - Debug Information ==="
            echo "Docker Container Status:"
            docker ps -a | grep api-gateway
            echo "Container Logs:"
            docker logs api-gateway --tail 100
            echo "Eureka Registration Status:"
            curl -s http://craftpilot:13579ada@localhost:8761/eureka/apps/API-GATEWAY || true
            exit 1

      - name: Trigger Deploy Services Workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: trigger-deploy-services
