name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Create GCP credentials secret
        run: |
          echo "$GCP_CREDENTIALS" > gcp-credentials.json
          kubectl create secret generic gcp-credentials --from-file=gcp-credentials.json -n default --dry-run=client -o yaml | kubectl apply -f -
          kubectl create secret generic gcp-config --from-literal=project-id=$GCP_PROJECT_ID -n default --dry-run=client -o yaml | kubectl apply -f -
        env:
          GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:$GITHUB_SHA .
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/my-app:$GITHUB_SHA

      - name: Deploy to Kubernetes
        run: |
          kubectl set image deployment/my-app my-app=${{ secrets.DOCKER_USERNAME }}/my-app:$GITHUB_SHA
