name: Deploy Services

on:
  workflow_dispatch:
  push:
    branches: [master]
    paths:
      - "docker-compose.yml"
      - "deploy.sh"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          EUREKA_USERNAME: craftpilot
          EUREKA_PASSWORD: ${{ secrets.EUREKA_PASSWORD }}
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REDIS_PASSWORD: ${{ secrets.REDIS_PASSWORD }}
          GMAIL_SERVICE_ACCOUNT: ${{ secrets.GMAIL_SERVICE_ACCOUNT }}
          GRAFANA_ADMIN_PASSWORD: ${{ secrets.GRAFANA_ADMIN_PASSWORD }}
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKERHUB_USERNAME,DOCKERHUB_TOKEN,EUREKA_USERNAME,EUREKA_PASSWORD,GCP_SA_KEY,GCP_PROJECT_ID,REDIS_PASSWORD,GMAIL_SERVICE_ACCOUNT,GRAFANA_ADMIN_PASSWORD
          script: |
            # Proje dizinini oluştur
            mkdir -p /opt/craftpilot
            cd /opt/craftpilot

            # Mevcut dosyaları yedekle
            if [ -f "docker-compose.yml" ]; then
              mv docker-compose.yml docker-compose.yml.backup
            fi
            if [ -f "deploy.sh" ]; then
              mv deploy.sh deploy.sh.backup
            fi

            # Gerekli dosyaları oluştur
            cat << 'EOF' > docker-compose.yml
            $(cat $GITHUB_WORKSPACE/docker-compose.yml)
            EOF

            cat << 'EOF' > deploy.sh
            #!/bin/bash

            # .env dosyasını oluştur
            cat << ENVEOF > .env
            DOCKERHUB_USERNAME=${DOCKERHUB_USERNAME}
            EUREKA_USERNAME=${EUREKA_USERNAME}
            EUREKA_PASSWORD=${EUREKA_PASSWORD}
            GCP_SA_KEY_PATH=/opt/craftpilot/gcp-credentials.json
            GCP_PROJECT_ID=${GCP_PROJECT_ID}
            REDIS_PASSWORD=${REDIS_PASSWORD}
            GMAIL_SERVICE_ACCOUNT=${GMAIL_SERVICE_ACCOUNT}
            GRAFANA_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
            VERSION=latest
            ENVEOF

            # GCP credentials dosyasını oluştur
            echo "${GCP_SA_KEY}" > /opt/craftpilot/gcp-credentials.json
            chmod 600 /opt/craftpilot/gcp-credentials.json

            # Docker Compose ile servisleri başlat
            docker-compose pull
            docker-compose up -d

            # Servislerin durumunu kontrol et
            docker-compose ps
            EOF

            # Dosya izinlerini ayarla
            chmod +x deploy.sh

            # GCP credentials dizinini oluştur
            mkdir -p /opt/craftpilot

            # GCP credentials dosyasını oluştur
            echo "$GCP_SA_KEY" > /opt/craftpilot/gcp-credentials.json
            chmod 600 /opt/craftpilot/gcp-credentials.json

            # Deploy script'i çalıştır
            ./deploy.sh

            # Hata kontrolü
            if [ $? -ne 0 ]; then
              echo "Deployment failed!"
              docker-compose logs
              exit 1
            fi

            # Sağlık kontrolü
            echo "Checking service health..."
            sleep 30

            # Eureka kontrolü
            if ! curl -s http://localhost:8761/actuator/health | grep -q "UP"; then
              echo "Eureka Server is not healthy!"
              docker-compose logs eureka-server
              exit 1
            fi

            echo "Deployment completed successfully!"
