name: Eureka Server CI/CD

on:
  push:
    branches: [master]
    paths:
      - "eureka-server/**"
      - ".github/workflows/eureka-server-ci-cd.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Grant execute permission for mvnw
        run: |
          cd eureka-server
          chmod +x mvnw

      - name: Build
        run: |
          cd eureka-server
          ./mvnw clean package -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./eureka-server
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:latest-arm64

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Infrastructure setup
            docker network create craftpilot-network || true

            # Deploy Eureka Server
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:latest-arm64
            docker stop eureka-server || true
            docker rm eureka-server || true

            docker run -d \
              --name eureka-server \
              --hostname eureka-server \
              --network craftpilot-network \
              --restart unless-stopped \
              -p 8761:8761 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e EUREKA_USERNAME=craftpilot \
              -e EUREKA_PASSWORD=13579ada \
              -e SERVER_PORT=8761 \
              -e EUREKA_INSTANCE_HOSTNAME=eureka-server \
              -e EUREKA_CLIENT_REGISTER_WITH_EUREKA=false \
              -e EUREKA_CLIENT_FETCH_REGISTRY=false \
              -e MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info \
              -e MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always \
              ${{ secrets.DOCKERHUB_USERNAME }}/eureka-server:latest-arm64

            # Wait for container to start
            echo "Waiting for container to start..."
            sleep 20

            # Check if container is running
            if ! docker ps | grep -q eureka-server; then
              echo "Container failed to start"
              docker logs eureka-server
              exit 1
            fi

            # Multiple health check methods
            echo "Performing health checks..."
            max_attempts=5
            attempt=1
            success=false

            while [ $attempt -le $max_attempts ]; do
              echo "Health check attempt $attempt/$max_attempts"
              
              # Method 1: Check actuator endpoint
              if curl -sf -u craftpilot:13579ada http://localhost:8761/actuator/health | grep -q "UP"; then
                success=true
                break
              fi
              
              # Method 2: Check Eureka dashboard
              if curl -sf http://localhost:8761 | grep -q "Eureka"; then
                success=true
                break
              fi
              
              # Method 3: Check application logs
              if docker logs eureka-server 2>&1 | grep -q "Started EurekaServerApplication"; then
                success=true
                break
              fi
              
              attempt=$((attempt + 1))
              sleep 10
            done

            if [ "$success" = true ]; then
              echo "Service is healthy and running"
              exit 0
            else
              echo "Service health check failed"
              docker logs eureka-server
              exit 1

      - name: Trigger Deploy Services Workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: trigger-deploy-services
