name: Image Service CI/CD

on:
  push:
    branches: [master]
    paths:
      - "image-service/**"
      - ".github/workflows/image-service-ci-cd.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Grant execute permission for mvnw
        run: |
          cd image-service
          chmod +x mvnw

      - name: Build
        run: |
          cd image-service
          ./mvnw clean package -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./image-service
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/image-service:latest-arm64

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Infrastructure containers
            docker network create craftpilot-network || true

            # Start Redis if not running
            if ! docker ps | grep -q redis; then
              docker run -d \
                --name redis \
                --network craftpilot-network \
                -p 6379:6379 \
                -e REDIS_PASSWORD=13579ada \
                redis:latest --requirepass 13579ada
            fi

            # Deploy Image Service
            echo "=== Deploying Image Service ==="
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/image-service:latest-arm64
            docker stop image-service || true
            docker rm image-service || true

            docker run -d \
              --name image-service \
              --network craftpilot-network \
              --restart unless-stopped \
              -p 8056:8056 \
              -v /opt/craftpilot/gcp-credentials.json:/gcp-credentials.json:ro \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e KAFKA_BOOTSTRAP_SERVERS=kafka:9092 \
              -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://craftpilot:13579ada@eureka-server:8761/eureka/ \
              -e GOOGLE_APPLICATION_CREDENTIALS=/gcp-credentials.json \
              -e SPRING_SECURITY_USER_NAME=craftpilot \
              -e SPRING_SECURITY_USER_PASSWORD=13579ada \
              -e SPRING_REDIS_HOST=redis \
              -e SPRING_REDIS_PORT=6379 \
              -e SPRING_REDIS_PASSWORD=13579ada \
              -e MANAGEMENT_HEALTH_VALIDATE_GROUP_MEMBERSHIP=false \
              -e SPRING_CLOUD_GCP_PROJECT_ID=craft-pilot-ai \
              -e IMAGE_STORAGE_BUCKET_NAME=${{ secrets.GCP_STORAGE_BUCKET }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/image-service:latest-arm64

            echo "=== Waiting for initial startup ==="
            sleep 15

            # Simple and fast health check
            echo "=== Starting health checks ==="
            MAX_ATTEMPTS=6
            ATTEMPT=1
            WAIT_SECONDS=10

            while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
              echo "Health check attempt $ATTEMPT of $MAX_ATTEMPTS"
              
              # Check if container is running
              if ! docker ps | grep -q image-service; then
                echo "Container is not running"
                docker ps -a | grep image-service
                docker logs image-service --tail 50
                exit 1
              fi

              # Quick health endpoint check
              HEALTH_STATUS=$(curl -s -m 5 http://localhost:8056/actuator/health | grep -o '"status":"[^"]*' | cut -d'"' -f4 || echo "UNKNOWN")
              
              if [ "$HEALTH_STATUS" = "UP" ]; then
                echo "✅ Service is healthy and ready!"
                exit 0
              fi

              echo "Current health status: $HEALTH_STATUS"
              echo "Waiting ${WAIT_SECONDS} seconds before next attempt..."
              sleep $WAIT_SECONDS
              ATTEMPT=$((ATTEMPT + 1))
            done

            echo "❌ Health check failed after $MAX_ATTEMPTS attempts"
            echo "=== Final Debug Information ==="
            docker ps -a | grep image-service
            docker logs image-service --tail 100
            exit 1

      - name: Trigger Deploy Services Workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: trigger-deploy-services
