name: Image Service CI/CD

on:
  push:
    branches: [master]
    paths:
      - "image-service/**"
      - ".github/workflows/image-service-ci-cd.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Grant execute permission for mvnw
        run: |
          cd image-service
          chmod +x mvnw

      - name: Build
        run: |
          cd image-service
          ./mvnw clean package -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./image-service
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/image-service:latest-arm64

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |

            # Deploy Image Service
            echo "=== Deploying Image Service ==="
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/image-service:latest-arm64
            docker stop image-service || true
            docker rm image-service || true

            docker run -d \
              --name image-service \
              --network craftpilot-network \
              --restart unless-stopped \
              --health-cmd="curl -f http://localhost:8056/actuator/health || exit 1" \
              --health-interval=30s \
              --health-retries=3 \
              --health-timeout=10s \
              --health-start-period=60s \
              -p 8056:8056 \
              -v /opt/craftpilot/gcp-credentials.json:/gcp-credentials.json:ro \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e KAFKA_BOOTSTRAP_SERVERS=kafka:9092 \
              -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://craftpilot:CHANGE_ME_IN_PRODUCTION@eureka-server:8761/eureka/ \
              -e GOOGLE_APPLICATION_CREDENTIALS=/gcp-credentials.json \
              -e SPRING_SECURITY_USER_NAME=craftpilot \
              -e SPRING_SECURITY_USER_PASSWORD=CHANGE_ME_IN_PRODUCTION \
              -e SPRING_DATA_REDIS_HOST=redis \
              -e SPRING_DATA_REDIS_PORT=6379 \
              -e SPRING_DATA_REDIS_PASSWORD=CHANGE_ME_IN_PRODUCTION \
              -e MANAGEMENT_HEALTH_VALIDATE_GROUP_MEMBERSHIP=false \
              -e SPRING_CLOUD_GCP_PROJECT_ID=craft-pilot-ai \
              -e IMAGE_STORAGE_BUCKET_NAME=${{ secrets.GCP_STORAGE_BUCKET }} \
              -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
              ${{ secrets.DOCKERHUB_USERNAME }}/image-service:latest-arm64

            # Install curl in the container for health checks
            docker exec image-service apt-get update && docker exec image-service apt-get install -y curl

            echo "=== Waiting for initial startup ==="
            sleep 60

            echo "=== Checking service health ==="
            MAX_ATTEMPTS=10
            ATTEMPT=1

            while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
              echo "Health check attempt $ATTEMPT/$MAX_ATTEMPTS"
              
              # Check container status
              CONTAINER_STATUS=$(docker inspect --format='{{.State.Status}}' image-service)
              if [ "$CONTAINER_STATUS" != "running" ]; then
                echo "Container is not running. Current status: $CONTAINER_STATUS"
                docker logs image-service
                exit 1
              fi

              # Check application health
              HEALTH_CHECK=$(docker exec image-service curl -s -w "\n%{http_code}" http://localhost:8056/actuator/health)
              HTTP_CODE=$(echo "$HEALTH_CHECK" | tail -n1)
              HEALTH_STATUS=$(echo "$HEALTH_CHECK" | head -n1)
              
              if [ "$HTTP_CODE" = "200" ] && echo "$HEALTH_STATUS" | grep -q '"status":"UP"'; then
                echo "Service is healthy!"
                # Verify Eureka registration
                if docker logs image-service | grep -q "registration status: 204"; then
                  echo "Successfully registered with Eureka"
                  exit 0
                fi
              fi
              
              if [ $ATTEMPT -eq 5 ]; then
                echo "=== Mid-point debug information ==="
                echo "Container Status:"
                docker ps | grep image-service
                echo "Recent Logs:"
                docker logs image-service --tail 100
              fi
              
              echo "Waiting before next attempt..."
              sleep 30
              ATTEMPT=$((ATTEMPT + 1))
            done

            echo "=== Health check failed - Debug information ==="
            echo "Final Container Status:"
            docker inspect image-service | grep -A 10 "Health"
            echo "Container Logs:"
            docker logs image-service
            exit 1
