name: Lighthouse Service CI/CD

on:
  push:
    branches: [master]
    paths:
      - "lighthouse-service/**"
      - ".github/workflows/lighthouse-service-ci-cd.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "prod"
        type: choice
        options:
          - prod
          - debug

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Generate Maven Wrapper if not exists
        run: |
          cd lighthouse-service
          if [ ! -f "mvnw" ]; then
            echo "Maven Wrapper not found, generating it..."
            mvn -N wrapper:wrapper -Dmaven=3.9.5
          fi
          chmod +x mvnw

      - name: Build
        run: |
          cd lighthouse-service
          ./mvnw clean package -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./lighthouse-service
          platforms: linux/arm64
          push: true
          provenance: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/lighthouse-service:latest-arm64

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /opt/craftpilot/tmp/netty
            mkdir -p /opt/craftpilot/tmp/lighthouse

            # Stop and remove previous container
            echo "Stopping and removing previous container if it exists"
            docker stop lighthouse-service || true
            docker rm lighthouse-service || true

            # Pull the latest image with explicit platform for ARM64
            echo "Pulling latest ARM64 image"
            docker pull --platform linux/arm64 ${{ secrets.DOCKERHUB_USERNAME }}/lighthouse-service:latest-arm64

            echo "Starting container with proper environment variables"
            docker run -d \
              --platform linux/arm64 \
              --name lighthouse-service \
              --network craftpilot-network \
              --restart unless-stopped \
              -p 8085:8085 \
              -v /opt/craftpilot/tmp/lighthouse:/tmp/lighthouse \
              -v /opt/craftpilot/tmp/netty:/tmp/netty \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e SPRING_DATA_REDIS_HOST=redis \
              -e SPRING_DATA_REDIS_PASSWORD=13579ada \
              -e LIGHTHOUSE_CLI_PATH=/usr/local/bin/lighthouse \
              -e CHROME_PATH=/usr/bin/google-chrome \
              -e LIGHTHOUSE_CHROMIUM_PATH=/usr/bin/google-chrome \
              --ulimit nofile=65536:65536 \
              --security-opt no-new-privileges \
              --health-cmd="curl -f http://localhost:8085/health || exit 1" \
              --health-interval=30s \
              --health-timeout=10s \
              --health-retries=5 \
              --health-start-period=60s \
              ${{ secrets.DOCKERHUB_USERNAME }}/lighthouse-service:latest-arm64

            # Verify available tools in the container
            echo "Waiting for container to start (10 seconds)..."
            sleep 10

            echo "Verifying critical tools in container..."
            docker exec lighthouse-service java -version || echo "Java check failed"
            docker exec lighthouse-service node --version || echo "Node.js check failed"
            docker exec lighthouse-service npm --version || echo "NPM check failed"
            docker exec lighthouse-service which lighthouse || echo "Lighthouse CLI check failed"
            docker exec lighthouse-service lighthouse --version || echo "Lighthouse version check failed"

            echo "Validating container environment variables..."
            docker exec lighthouse-service printenv | grep -E "PATH|NODE_PATH|JAVA_HOME|CHROME"

            echo "=== Waiting for service startup ==="
            max_attempts=30
            counter=0
            success=0

            while [ $counter -lt $max_attempts ]; do
              echo "Health check attempt $((counter + 1))/$max_attempts"
              
              # Container durumu kontrolü
              if ! docker ps --filter "name=lighthouse-service" --format '{{.Status}}' | grep -q "Up"; then
                echo "Container is not running anymore. Checking logs..."
                docker logs lighthouse-service | tail -n 100
                exit 1
              fi
              
              # Application log kontrolü
              if docker logs lighthouse-service 2>&1 | grep -q "Started LighthouseServiceApplication"; then
                echo "Application startup completed"
                
                # Health check kontrolü
                HEALTH_CHECK=$(curl -s http://localhost:8085/health)
                if echo "$HEALTH_CHECK" | grep -q '"status":"UP"'; then
                  echo "✓ Health check passed: $HEALTH_CHECK"
                  success=1
                  break
                elif echo "$HEALTH_CHECK" | grep -q '"redis":"DOWN"'; then
                  echo "× Redis connection issue detected in health check"
                  echo "Health response: $HEALTH_CHECK"
                  # Redis sağlık bilgilerini göster
                  echo "Redis connection details from logs:"
                  docker logs lighthouse-service 2>&1 | grep -i "redis\|lettuce" | tail -20
                else
                  echo "× Health check failed with response: $HEALTH_CHECK"
                fi
              else
                echo "Waiting for application startup..."
              fi
              
              echo "Waiting for service to start... ($((counter + 1))/$max_attempts)"
              sleep 10
              counter=$((counter + 1))
            done

            if [ $success -eq 1 ]; then
              echo "=== Deployment completed successfully ==="
              exit 0
            else
              echo "=== Health check failed - Debug Information ==="
              echo "Docker Status:"
              docker ps -a | grep lighthouse-service
              echo "Container Logs:"
              docker logs lighthouse-service --tail 100
              echo "Health Check Response:"
              curl -v http://localhost:8085/health || true
              echo "Redis Check:"
              docker exec lighthouse-service sh -c 'nc -zv $SPRING_DATA_REDIS_HOST $SPRING_DATA_REDIS_PORT' || echo "Redis connection failed"
              exit 1
            fi
