name: LLM Service CI/CD

on:
  push:
    branches: [master]
    paths:
      - "llm-service/**"
      - ".github/workflows/llm-service-ci-cd.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./llm-service
    steps:
      - uses: actions/checkout@v3

      # QEMU kurulumu
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      # Docker Buildx kurulumu
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64
          buildkitd-flags: --debug

      # Docker Hub'a giriş yap
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build ve Push
      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./llm-service
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/llm-service:latest-arm64
            ${{ secrets.DOCKERHUB_USERNAME }}/llm-service:${{ github.sha }}-arm64
          no-cache: true
          pull: true

      # VPS'e deploy
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "=== Creating GCP Credentials ==="
            echo "${{ secrets.GCP_SA_KEY }}" > /tmp/gcp-credentials.json

            echo "=== Pulling ARM64 Image ==="
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/llm-service:latest-arm64

            echo "=== Stopping Old Container ==="
            docker stop llm-service || true
            docker rm llm-service || true

            echo "=== Starting New Container ==="
            docker run -d \
              --name llm-service \
              --platform linux/arm64 \
              --network craftpilot-network \
              -p 8062:8062 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://craftpilot:13579ada@eureka-server:8057/eureka/ \
              -e GOOGLE_APPLICATION_CREDENTIALS=/gcp-credentials.json \
              -e SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092 \
              -e SPRING_REDIS_HOST=redis \
              -e SPRING_REDIS_PORT=6379 \
              -v /tmp/gcp-credentials.json:/gcp-credentials.json:ro \
              ${{ secrets.DOCKERHUB_USERNAME }}/llm-service:latest-arm64

            echo "=== Waiting for Container to Start ==="
            sleep 60

            echo "=== Container Logs ==="
            docker logs llm-service

            echo "=== Health Check ==="
            for i in {1..5}; do
              if curl -f http://localhost:8062/actuator/health; then
                echo "Service is healthy"
                exit 0
              fi
              echo "Attempt $i: Waiting for service to start..."
              sleep 10
            done
            echo "Service failed health check"
            docker logs llm-service
            exit 1

      - name: Trigger Deploy Services Workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: trigger-deploy-services
