name: Redis Service CI/CD

on:
  push:
    branches: [master]
    paths:
      - "redis-service/**"
      - ".github/workflows/redis-service-ci-cd.yml"
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./redis-service
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Grant execute permission for mvnw
        run: chmod +x mvnw

      - name: Build
        run: ./mvnw clean package -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./redis-service
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/redis-service:latest-arm64
            ${{ secrets.DOCKERHUB_USERNAME }}/redis-service:${{ github.sha }}-arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/redis-service:buildcache-arm64
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/redis-service:buildcache-arm64,mode=max

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Infrastructure network
            docker network create craftpilot-network || true

            # Mevcut container'ı kaldır
            docker stop redis-service || true
            docker rm redis-service || true

            # Yeni container'ı başlat
            docker run -d \
              --name redis-service \
              --network craftpilot-network \
              --restart unless-stopped \
              -p 8064:8064 \
              -e SPRING_PROFILES_ACTIVE=prod \
              -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://craftpilot:13579ada@eureka-server:8761/eureka/ \
              -e SPRING_REDIS_HOST=redis \
              -e SPRING_REDIS_PORT=6379 \
              -e SPRING_REDIS_PASSWORD=13579ada \
              -e MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always \
              -e MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true \
              -e MANAGEMENT_HEALTH_VALIDATE_GROUP_MEMBERSHIP=false \
              ${{ secrets.DOCKERHUB_USERNAME }}/redis-service:latest-arm64

            # Health check
            echo "Starting health checks..."
            for i in {1..30}; do
              echo "Attempt $i: Checking service health..."
              
              HEALTH_STATUS=$(curl -s http://localhost:8064/actuator/health || echo "Failed to connect")
              echo "Health status: $HEALTH_STATUS"
              
              if echo "$HEALTH_STATUS" | grep -q "UP"; then
                echo "Service is healthy!"
                exit 0
              fi
              
              if [ $i -eq 15 ]; then
                echo "Mid-point container logs:"
                docker logs redis-service
              fi
              
              sleep 10
            done

            echo "Service failed to become healthy within timeout"
            echo "Final container logs:"
            docker logs redis-service
            exit 1

      - name: Trigger Deploy Services Workflow
        if: success()
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          event-type: trigger-deploy-services
