name: Test SSH Connection

on: workflow_dispatch

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Test SSH Connection
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true
          script: |
            echo "=== System Info ==="
            uname -a
            echo "=== User Info ==="
            whoami
            echo "=== Current Directory ==="
            pwd
            echo "=== SSH Directory Permissions ==="
            ls -la ~/.ssh
            echo "=== Testing Directory Creation ==="
            mkdir -p /opt/craftpilot
            echo "=== Docker Status ==="
            docker ps 