name: User Memory Service CI/CD

on:
  push:
    branches: [master]
    paths:
      - "user-memory-service/**"
      - ".github/workflows/user-memory-service-ci-cd.yml"
  pull_request:
    branches: [master]
    paths:
      - "user-memory-service/**"
      - ".github/workflows/user-memory-service-ci-cd.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy to"
        required: true
        default: "prod"
        type: choice
        options:
          - prod
          - debug

env:
  SERVICE_NAME: user-memory-service
  CONTAINER_PORT: 8067
  DOCKER_REGISTRY: craftpilot
  IMAGE_TAG: latest-arm64
  MANAGEMENT_PORT: 8067

jobs:
  build-and-deploy:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./user-memory-service
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/arm64

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          logout: true

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./user-memory-service
          platforms: linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}-arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:buildcache-arm64
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:buildcache-arm64,mode=max
          build-args: |
            SKIP_TESTS=true

      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: "20m"
          debug: true
          script: |
            set -e  # Exit on any error

            echo "=== Testing SSH Connection ==="
            whoami
            pwd

            echo "=== System Architecture ==="
            uname -m

            echo "=== Creating Directory Structure ==="
            mkdir -p /opt/craftpilot

            # MongoDB container check
            MONGODB_CONTAINER="craftpilot-mongodb"
            if ! docker ps | grep -q "$MONGODB_CONTAINER"; then
              echo "WARNING: Default MongoDB container not found ($MONGODB_CONTAINER)"
              # Still try to detect any MongoDB container as fallback
              MONGODB_CONTAINER=$(docker ps --format '{{.Names}}' | grep -E 'mongo|mongodb' | head -n 1)
              if [ -z "$MONGODB_CONTAINER" ]; then
                echo "ERROR: No MongoDB container found! Using default name, but connection may fail."
                MONGODB_CONTAINER="craftpilot-mongodb" # Fallback to default
              else
                echo "Found alternative MongoDB container: $MONGODB_CONTAINER"
              fi
            fi
            echo "Using MongoDB container: $MONGODB_CONTAINER"

            # MongoDB URI configuration
            if [ -n "${{ secrets.MONGODB_URI }}" ]; then
              # Parse the URI and replace the hostname with our container name
              # Extract parts before and after hostname
              URI_PREFIX=$(echo "${{ secrets.MONGODB_URI }}" | grep -oP 'mongodb://[^@]+@')
              URI_SUFFIX=$(echo "${{ secrets.MONGODB_URI }}" | grep -oP '(?<=@)[^/]+/.*')
              URI_HOST=$(echo "$URI_SUFFIX" | grep -oP '^[^:/]+')
              URI_REMAINDER=$(echo "$URI_SUFFIX" | grep -oP '(?<='"$URI_HOST"')[:/].*')
              
              # Build URI with the correct container name
              MONGODB_URI="${URI_PREFIX}${MONGODB_CONTAINER}${URI_REMAINDER}"
              echo "Modified MongoDB URI with correct container name: $(echo $MONGODB_URI | sed 's/:[^:]*@/:*****@/g')"
            else
              # Build URI from components
              MONGODB_URI="mongodb://${{ secrets.MONGO_ROOT_USERNAME }}:${{ secrets.MONGO_ROOT_PASSWORD }}@${MONGODB_CONTAINER}:27017/craftpilot_user_memory_db?authSource=admin&retryWrites=true&w=majority&serverSelectionTimeoutMS=60000"
              echo "Built MongoDB URI from credential components: $(echo $MONGODB_URI | sed 's/:[^:]*@/:*****@/g')"
            fi

            # Test MongoDB connection before deployment
            echo "Testing MongoDB connection..."
            if docker run --rm --network craftpilot-network mongo:6.0 mongosh --quiet --eval "db.runCommand({ping:1}).ok" admin --host $MONGODB_CONTAINER --port 27017 -u ${{ secrets.MONGO_ROOT_USERNAME }} -p ${{ secrets.MONGO_ROOT_PASSWORD }} --authenticationDatabase admin | grep -q "1"; then
              echo "✅ MongoDB connection test successful!"
            else
              echo "⚠️ MongoDB connection test failed! Deployment will continue but may have issues."
              echo "Checking MongoDB container status:"
              docker ps | grep -i $MONGODB_CONTAINER || echo "Container not found!"
            fi

            echo "=== Stopping Old Container ==="
            docker rm -f ${{ env.SERVICE_NAME }} || true

            echo "=== Starting User Memory Service ==="
            if [[ "${{ github.event.inputs.environment }}" == "debug" ]]; then
              docker run -d \
                --name ${{ env.SERVICE_NAME }} \
                --network craftpilot-network \
                --restart unless-stopped \
                -p ${{ env.CONTAINER_PORT }}:${{ env.CONTAINER_PORT }} \
                -p 5008:5008 \
                -e SPRING_PROFILES_ACTIVE=prod \
                -e SERVER_PORT=${{ env.CONTAINER_PORT }} \
                -e MANAGEMENT_SERVER_PORT=${{ env.MANAGEMENT_PORT }} \
                -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://craftpilot:TEST123@eureka-server:8761/eureka/ \
                -e EUREKA_INSTANCE_HOSTNAME=${{ env.SERVICE_NAME }} \
                -e EUREKA_INSTANCE_PREFER_IP_ADDRESS=false \
                -e REDIS_HOST=redis \
                -e REDIS_PORT=6379 \
                -e REDIS_PASSWORD=TEST123 \
                -e SPRING_DATA_MONGODB_URI="$MONGODB_URI" \
                -e SPRING_DATA_MONGODB_DATABASE=craftpilot_user_memory_db \
                -e SPRING_DATA_MONGODB_CONNECT_TIMEOUT=60000 \
                -e SPRING_DATA_MONGODB_SOCKET_TIMEOUT=60000 \
                -e SPRING_DATA_MONGODB_MAX_WAIT_TIME=120000 \
                -e MANAGEMENT_HEALTH_VALIDATE_GROUP_MEMBERSHIP=false \
                -e MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true \
                -e MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED=true \
                -e MANAGEMENT_HEALTH_READINESSSTATE_ENABLED=true \
                -e MANAGEMENT_HEALTH_MONGODB_ENABLED=true \
                -e MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE="health,info,metrics,prometheus" \
                -e MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always \
                -e SPRING_APPLICATION_NAME=${{ env.SERVICE_NAME }} \
                -e LOGGING_LEVEL_COM_CRAFTPILOT=DEBUG \
                -e LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_MONGODB=DEBUG \
                -e LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_CLOUD_NETFLIX_EUREKA=DEBUG \
                -e "JAVA_TOOL_OPTIONS=-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5008" \
                ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }}
            else
              docker run -d \
                --name ${{ env.SERVICE_NAME }} \
                --network craftpilot-network \
                --restart unless-stopped \
                -p ${{ env.CONTAINER_PORT }}:${{ env.CONTAINER_PORT }} \
                -e SPRING_PROFILES_ACTIVE=prod \
                -e SERVER_PORT=${{ env.CONTAINER_PORT }} \
                -e MANAGEMENT_SERVER_PORT=${{ env.MANAGEMENT_PORT }} \
                -e EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://craftpilot:TEST123@eureka-server:8761/eureka/ \
                -e EUREKA_INSTANCE_HOSTNAME=${{ env.SERVICE_NAME }} \
                -e EUREKA_INSTANCE_PREFER_IP_ADDRESS=false \
                -e REDIS_HOST=redis \
                -e REDIS_PORT=6379 \
                -e REDIS_PASSWORD=TEST123 \
                -e SPRING_DATA_MONGODB_URI="$MONGODB_URI" \
                -e SPRING_DATA_MONGODB_DATABASE=craftpilot_user_memory_db \
                -e SPRING_DATA_MONGODB_CONNECT_TIMEOUT=60000 \
                -e SPRING_DATA_MONGODB_SOCKET_TIMEOUT=60000 \
                -e SPRING_DATA_MONGODB_MAX_WAIT_TIME=120000 \
                -e MANAGEMENT_HEALTH_VALIDATE_GROUP_MEMBERSHIP=false \
                -e MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED=true \
                -e MANAGEMENT_HEALTH_LIVENESSSTATE_ENABLED=true \
                -e MANAGEMENT_HEALTH_READINESSSTATE_ENABLED=true \
                -e MANAGEMENT_HEALTH_MONGODB_ENABLED=true \
                -e MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE="health,info,metrics,prometheus" \
                -e MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always \
                -e SPRING_APPLICATION_NAME=${{ env.SERVICE_NAME }} \
                -e LOGGING_LEVEL_COM_CRAFTPILOT=INFO \
                -e LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_DATA_MONGODB=INFO \
                ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.SERVICE_NAME }}:${{ env.IMAGE_TAG }}
            fi

            echo "=== Waiting for Service to Start ==="
            max_attempts=20
            counter=0

            while [ $counter -lt $max_attempts ]; do
              echo "Health check attempt $((counter + 1))/$max_attempts"
              
              # Container status check
              if ! docker ps --filter "name=${{ env.SERVICE_NAME }}" --format '{{.Status}}' | grep -q "Up"; then
                echo "Container is not running anymore. Checking logs..."
                docker logs ${{ env.SERVICE_NAME }} --tail 100
                exit 1
              fi
              
              # Health check
              HEALTH_CHECK=$(curl -s http://localhost:${{ env.CONTAINER_PORT }}/actuator/health || echo "Failed to connect")
              
              if echo "$HEALTH_CHECK" | grep -q '"status":"UP"'; then
                # Try to parse with jq if available
                if command -v jq &> /dev/null; then
                  MONGO_STATUS=$(echo "$HEALTH_CHECK" | jq -r '.components.mongo.status' 2>/dev/null || echo "UNKNOWN")
                  if [ "$MONGO_STATUS" = "UP" ]; then
                    echo "✅ MongoDB component is healthy! (verified by jq)"
                    echo "=== Deployment completed successfully ==="
                    exit 0
                  elif echo "$HEALTH_CHECK" | grep -q '"mongo":{.*"status":"UP"'; then
                    echo "✅ MongoDB component is healthy! (verified by grep)"
                    echo "=== Deployment completed successfully ==="
                    exit 0
                  else
                    echo "⚠️ Service is UP but MongoDB component status is: $MONGO_STATUS"
                  fi
                else
                  # Fallback if jq is not available - just check for the string pattern
                  if echo "$HEALTH_CHECK" | grep -q '"mongo".*"status":"UP"'; then
                    echo "✅ MongoDB component appears to be healthy based on string search"
                    echo "=== Deployment completed successfully ==="
                    exit 0
                  fi
                  
                  # Additional fallback - if overall status is UP for 3 consecutive checks, accept it
                  if [ $counter -ge 10 ]; then
                    echo "✅ Service has been reporting UP status for multiple checks"
                    echo "Assuming deployment is successful despite unclear MongoDB status"
                    exit 0
                  fi
                fi
              else
                echo "Health check response: $HEALTH_CHECK"
              fi
              
              # Enhanced MongoDB connection diagnostics
              if [ $counter -eq 5 ] || [ $counter -eq 15 ]; then
                echo "--- MongoDB Connection Diagnostics ---"
                echo "MongoDB container status:"
                docker ps | grep $MONGODB_CONTAINER || echo "MongoDB container not running!"
                
                echo "Testing network connectivity from user-memory-service to MongoDB:"
                docker exec ${{ env.SERVICE_NAME }} nc -zv $MONGODB_CONTAINER 27017 || echo "Cannot connect to MongoDB"
                
                echo "Container environment variables:"
                docker exec ${{ env.SERVICE_NAME }} env | grep -E 'MONGO|DB_|mongodb' || echo "No MongoDB env vars found"
                
                echo "Network details:"
                docker network inspect craftpilot-network | grep -A 5 -E "$MONGODB_CONTAINER|${{ env.SERVICE_NAME }}" || echo "Network inspection failed"
              fi
              
              echo "Waiting for service to start... ($((counter + 1))/$max_attempts)"
              sleep 15
              counter=$((counter + 1))
            done

            echo "=== Service Failed to Start - Debug Information ==="
            echo "Docker Container Status:"
            docker ps -a | grep ${{ env.SERVICE_NAME }}
            echo "Container Logs (last 100 lines):"
            docker logs ${{ env.SERVICE_NAME }} --tail 100
            echo "Error Messages and Exceptions:"
            docker logs ${{ env.SERVICE_NAME }} 2>&1 | grep -i "error\|exception\|failed" | tail -20

            echo "=== Deployment Failed ==="
            exit 1
